use serde::{Deserialize, Serialize};

/// 1:1 translation of com.fumbbl.ffb.dialog.DialogId.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DialogId {
    INFORMATION,
    YES_OR_NO_QUESTION,
    GAME_COACH_PASSWORD,
    TEAM_CHOICE,
    COIN_CHOICE,
    RE_ROLL,
    RE_ROLL_PROPERTIES,
    RE_ROLL_FOR_TARGETS,
    RE_ROLL_BLOCK_FOR_TARGETS,
    SKILL_USE,
    PROGRESS_BAR,
    TEAM_SETUP,
    USE_APOTHECARY,
    USE_APOTHECARIES,
    USE_IGORS,
    USE_MORTUARY_ASSISTANTS,
    RECEIVE_CHOICE,
    FOLLOWUP_CHOICE,
    START_GAME,
    APOTHECARY_CHOICE,
    TOUCHBACK,
    INTERCEPTION,
    SETUP_ERROR,
    GAME_STATISTICS,
    WINNINGS_RE_ROLL,
    GAME_CHOICE,
    KEY_BINDINGS,
    BLOCK_ROLL,
    PLAYER_CHOICE,
    DEFENDER_ACTION,
    JOIN,
    CONCEDE_GAME,
    ABOUT,
    END_TURN,
    LEAVE_GAME,
    BRIBES,
    PILING_ON,
    BUY_INDUCEMENTS,
    SOUND_VOLUME,
    JOURNEYMEN,
    SCALING_FACTOR,
    CHAT_COMMANDS,
    KICK_SKILL,
    USE_IGOR,
    USE_MORTUARY_ASSISTANT,
    KICKOFF_RETURN,
    SWARMING,
    SWARMING_ERROR,
    PETTY_CASH,
    WIZARD_SPELL,
    USE_INDUCEMENT,
    PASS_BLOCK,
    BUY_CARDS,
    BUY_CARDS_AND_INDUCEMENTS,
    ARGUE_THE_CALL,
    SELECT_BLITZ_TARGET,
    OPPONENT_BLOCK_SELECTION,
    PILE_DRIVER,
    USE_CHAINSAW,
    BLOCK_ROLL_PARTIAL_RE_ROLL,
    INVALID_SOLID_DEFENCE,
    SELECT_SKILL,
    BRIBERY_AND_CORRUPTION_RE_ROLL,
    SELECT_GAZE_TARGET,
    CONFIRM_END_ACTION,
    CHANGE_LIST,
    SELECT_WEATHER,
    INFORMATION_OKAY,
    STORE_PROPERTIES_LOCAL,
    KICK_OFF_RESULT,
    BLOODLUST_ACTION,
    PENALTY_SHOOTOUT,
    REPLAY_MODE_CHOICE,
    CREDITS,
    CREDITS_LICENSE,
    BUY_PRAYERS_AND_INDUCEMENTS,
    BLOCK_ROLL_PROPERTIES,
    RE_ROLL_BLOCK_FOR_TARGETS_PROPERTIES,
    OPPONENT_BLOCK_SELECTION_PROPERTIES,
    PICK_UP_CHOICE,
    SELECT_KEYWORD,
    SELECT_POSITION,
    RE_ROLL_REGENERATION_MULTIPLE,
    PUNT_TO_CROWD,
}

impl DialogId {
    pub fn get_name(self) -> &'static str {
        match self {
            DialogId::INFORMATION => "information",
            DialogId::YES_OR_NO_QUESTION => "yesOrNoQuestion",
            DialogId::GAME_COACH_PASSWORD => "gameCoachPassword",
            DialogId::TEAM_CHOICE => "teamChoice",
            DialogId::COIN_CHOICE => "coinChoice",
            DialogId::RE_ROLL => "reRoll",
            DialogId::RE_ROLL_PROPERTIES => "reRollProperties",
            DialogId::RE_ROLL_FOR_TARGETS => "reRollForTargets",
            DialogId::RE_ROLL_BLOCK_FOR_TARGETS => "reRollBlockForTargets",
            DialogId::SKILL_USE => "skillUse",
            DialogId::PROGRESS_BAR => "progressBar",
            DialogId::TEAM_SETUP => "teamSetup",
            DialogId::USE_APOTHECARY => "useApothecary",
            DialogId::USE_APOTHECARIES => "useApothecaries",
            DialogId::USE_IGORS => "useIgors",
            DialogId::USE_MORTUARY_ASSISTANTS => "useMortuaryAssistants",
            DialogId::RECEIVE_CHOICE => "receiveChoice",
            DialogId::FOLLOWUP_CHOICE => "followupChoice",
            DialogId::START_GAME => "startGame",
            DialogId::APOTHECARY_CHOICE => "apothecaryChoice",
            DialogId::TOUCHBACK => "touchback",
            DialogId::INTERCEPTION => "interception",
            DialogId::SETUP_ERROR => "setupError",
            DialogId::GAME_STATISTICS => "gameStatistics",
            DialogId::WINNINGS_RE_ROLL => "winningsReRoll",
            DialogId::GAME_CHOICE => "gameChoice",
            DialogId::KEY_BINDINGS => "keyBindings",
            DialogId::BLOCK_ROLL => "blockRoll",
            DialogId::PLAYER_CHOICE => "playerChoice",
            DialogId::DEFENDER_ACTION => "defenderAction",
            DialogId::JOIN => "join",
            DialogId::CONCEDE_GAME => "concedeGame",
            DialogId::ABOUT => "about",
            DialogId::END_TURN => "endTurn",
            DialogId::LEAVE_GAME => "leaveGame",
            DialogId::BRIBES => "bribes",
            DialogId::PILING_ON => "pilingOn",
            DialogId::BUY_INDUCEMENTS => "buyInducements",
            DialogId::SOUND_VOLUME => "soundVolume",
            DialogId::JOURNEYMEN => "journeymen",
            DialogId::SCALING_FACTOR => "scalingFactor",
            DialogId::CHAT_COMMANDS => "chatCommands",
            DialogId::KICK_SKILL => "kickSkill",
            DialogId::USE_IGOR => "useIgor",
            DialogId::USE_MORTUARY_ASSISTANT => "useMortuaryAssistant",
            DialogId::KICKOFF_RETURN => "kickoffReturn",
            DialogId::SWARMING => "swarming",
            DialogId::SWARMING_ERROR => "swarmingError",
            DialogId::PETTY_CASH => "pettyCash",
            DialogId::WIZARD_SPELL => "wizardSpell",
            DialogId::USE_INDUCEMENT => "useInducement",
            DialogId::PASS_BLOCK => "passBlock",
            DialogId::BUY_CARDS => "buyCards",
            DialogId::BUY_CARDS_AND_INDUCEMENTS => "buyCardsAndInducements",
            DialogId::ARGUE_THE_CALL => "argueTheCall",
            DialogId::SELECT_BLITZ_TARGET => "selectBlitzTarget",
            DialogId::OPPONENT_BLOCK_SELECTION => "opponentBlockSelection",
            DialogId::PILE_DRIVER => "pileDriver",
            DialogId::USE_CHAINSAW => "useChainsaw",
            DialogId::BLOCK_ROLL_PARTIAL_RE_ROLL => "blockRollPartialReRoll",
            DialogId::INVALID_SOLID_DEFENCE => "invalidSolidDefence",
            DialogId::SELECT_SKILL => "selectSkill",
            DialogId::BRIBERY_AND_CORRUPTION_RE_ROLL => "briberyAndCorruptionReRoll",
            DialogId::SELECT_GAZE_TARGET => "selectGazeTarget",
            DialogId::CONFIRM_END_ACTION => "confirmEndAction",
            DialogId::CHANGE_LIST => "changeList",
            DialogId::SELECT_WEATHER => "selectWeather",
            DialogId::INFORMATION_OKAY => "informationOkay",
            DialogId::STORE_PROPERTIES_LOCAL => "storePropertiesLocal",
            DialogId::KICK_OFF_RESULT => "kickOffResult",
            DialogId::BLOODLUST_ACTION => "bloodlustAction",
            DialogId::PENALTY_SHOOTOUT => "penaltyShootout",
            DialogId::REPLAY_MODE_CHOICE => "replayModeChoice",
            DialogId::CREDITS => "credits",
            DialogId::CREDITS_LICENSE => "creditsLicense",
            DialogId::BUY_PRAYERS_AND_INDUCEMENTS => "buyPrayersAndInducements",
            DialogId::BLOCK_ROLL_PROPERTIES => "blockRollProperties",
            DialogId::RE_ROLL_BLOCK_FOR_TARGETS_PROPERTIES => "reRollBlockForTargetsProperties",
            DialogId::OPPONENT_BLOCK_SELECTION_PROPERTIES => "opponentBlockSelectionProperties",
            DialogId::PICK_UP_CHOICE => "pickUpChoice",
            DialogId::SELECT_KEYWORD => "selectKeyword",
            DialogId::SELECT_POSITION => "selectPosition",
            DialogId::RE_ROLL_REGENERATION_MULTIPLE => "reRollRegenerationMultiple",
            DialogId::PUNT_TO_CROWD => "puntToCrowd",
        }
    }

    pub fn for_name(name: &str) -> Option<DialogId> {
        match name {
            "information" => Some(DialogId::INFORMATION),
            "yesOrNoQuestion" => Some(DialogId::YES_OR_NO_QUESTION),
            "gameCoachPassword" => Some(DialogId::GAME_COACH_PASSWORD),
            "teamChoice" => Some(DialogId::TEAM_CHOICE),
            "coinChoice" => Some(DialogId::COIN_CHOICE),
            "reRoll" => Some(DialogId::RE_ROLL),
            "reRollProperties" => Some(DialogId::RE_ROLL_PROPERTIES),
            "reRollForTargets" => Some(DialogId::RE_ROLL_FOR_TARGETS),
            "reRollBlockForTargets" => Some(DialogId::RE_ROLL_BLOCK_FOR_TARGETS),
            "skillUse" => Some(DialogId::SKILL_USE),
            "progressBar" => Some(DialogId::PROGRESS_BAR),
            "teamSetup" => Some(DialogId::TEAM_SETUP),
            "useApothecary" => Some(DialogId::USE_APOTHECARY),
            "useApothecaries" => Some(DialogId::USE_APOTHECARIES),
            "useIgors" => Some(DialogId::USE_IGORS),
            "useMortuaryAssistants" => Some(DialogId::USE_MORTUARY_ASSISTANTS),
            "receiveChoice" => Some(DialogId::RECEIVE_CHOICE),
            "followupChoice" => Some(DialogId::FOLLOWUP_CHOICE),
            "startGame" => Some(DialogId::START_GAME),
            "apothecaryChoice" => Some(DialogId::APOTHECARY_CHOICE),
            "touchback" => Some(DialogId::TOUCHBACK),
            "interception" => Some(DialogId::INTERCEPTION),
            "setupError" => Some(DialogId::SETUP_ERROR),
            "gameStatistics" => Some(DialogId::GAME_STATISTICS),
            "winningsReRoll" => Some(DialogId::WINNINGS_RE_ROLL),
            "gameChoice" => Some(DialogId::GAME_CHOICE),
            "keyBindings" => Some(DialogId::KEY_BINDINGS),
            "blockRoll" => Some(DialogId::BLOCK_ROLL),
            "playerChoice" => Some(DialogId::PLAYER_CHOICE),
            "defenderAction" => Some(DialogId::DEFENDER_ACTION),
            "join" => Some(DialogId::JOIN),
            "concedeGame" => Some(DialogId::CONCEDE_GAME),
            "about" => Some(DialogId::ABOUT),
            "endTurn" => Some(DialogId::END_TURN),
            "leaveGame" => Some(DialogId::LEAVE_GAME),
            "bribes" => Some(DialogId::BRIBES),
            "pilingOn" => Some(DialogId::PILING_ON),
            "buyInducements" => Some(DialogId::BUY_INDUCEMENTS),
            "soundVolume" => Some(DialogId::SOUND_VOLUME),
            "journeymen" => Some(DialogId::JOURNEYMEN),
            "scalingFactor" => Some(DialogId::SCALING_FACTOR),
            "chatCommands" => Some(DialogId::CHAT_COMMANDS),
            "kickSkill" => Some(DialogId::KICK_SKILL),
            "useIgor" => Some(DialogId::USE_IGOR),
            "useMortuaryAssistant" => Some(DialogId::USE_MORTUARY_ASSISTANT),
            "kickoffReturn" => Some(DialogId::KICKOFF_RETURN),
            "swarming" => Some(DialogId::SWARMING),
            "swarmingError" => Some(DialogId::SWARMING_ERROR),
            "pettyCash" => Some(DialogId::PETTY_CASH),
            "wizardSpell" => Some(DialogId::WIZARD_SPELL),
            "useInducement" => Some(DialogId::USE_INDUCEMENT),
            "passBlock" => Some(DialogId::PASS_BLOCK),
            "buyCards" => Some(DialogId::BUY_CARDS),
            "buyCardsAndInducements" => Some(DialogId::BUY_CARDS_AND_INDUCEMENTS),
            "argueTheCall" => Some(DialogId::ARGUE_THE_CALL),
            "selectBlitzTarget" => Some(DialogId::SELECT_BLITZ_TARGET),
            "opponentBlockSelection" => Some(DialogId::OPPONENT_BLOCK_SELECTION),
            "pileDriver" => Some(DialogId::PILE_DRIVER),
            "useChainsaw" => Some(DialogId::USE_CHAINSAW),
            "blockRollPartialReRoll" => Some(DialogId::BLOCK_ROLL_PARTIAL_RE_ROLL),
            "invalidSolidDefence" => Some(DialogId::INVALID_SOLID_DEFENCE),
            "selectSkill" => Some(DialogId::SELECT_SKILL),
            "briberyAndCorruptionReRoll" => Some(DialogId::BRIBERY_AND_CORRUPTION_RE_ROLL),
            "selectGazeTarget" => Some(DialogId::SELECT_GAZE_TARGET),
            "confirmEndAction" => Some(DialogId::CONFIRM_END_ACTION),
            "changeList" => Some(DialogId::CHANGE_LIST),
            "selectWeather" => Some(DialogId::SELECT_WEATHER),
            "informationOkay" => Some(DialogId::INFORMATION_OKAY),
            "storePropertiesLocal" => Some(DialogId::STORE_PROPERTIES_LOCAL),
            "kickOffResult" => Some(DialogId::KICK_OFF_RESULT),
            "bloodlustAction" => Some(DialogId::BLOODLUST_ACTION),
            "penaltyShootout" => Some(DialogId::PENALTY_SHOOTOUT),
            "replayModeChoice" => Some(DialogId::REPLAY_MODE_CHOICE),
            "credits" => Some(DialogId::CREDITS),
            "creditsLicense" => Some(DialogId::CREDITS_LICENSE),
            "buyPrayersAndInducements" => Some(DialogId::BUY_PRAYERS_AND_INDUCEMENTS),
            "blockRollProperties" => Some(DialogId::BLOCK_ROLL_PROPERTIES),
            "reRollBlockForTargetsProperties" => Some(DialogId::RE_ROLL_BLOCK_FOR_TARGETS_PROPERTIES),
            "opponentBlockSelectionProperties" => Some(DialogId::OPPONENT_BLOCK_SELECTION_PROPERTIES),
            "pickUpChoice" => Some(DialogId::PICK_UP_CHOICE),
            "selectKeyword" => Some(DialogId::SELECT_KEYWORD),
            "selectPosition" => Some(DialogId::SELECT_POSITION),
            "reRollRegenerationMultiple" => Some(DialogId::RE_ROLL_REGENERATION_MULTIPLE),
            "puntToCrowd" => Some(DialogId::PUNT_TO_CROWD),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_name_round_trips() {
        let ids = [
            DialogId::RE_ROLL,
            DialogId::BLOCK_ROLL,
            DialogId::APOTHECARY_CHOICE,
            DialogId::FOLLOWUP_CHOICE,
            DialogId::TEAM_SETUP,
            DialogId::PUNT_TO_CROWD,
        ];
        for id in ids {
            assert_eq!(DialogId::for_name(id.get_name()), Some(id));
        }
    }

    #[test]
    fn unknown_name_returns_none() {
        assert_eq!(DialogId::for_name("nonExistent"), None);
    }

    #[test]
    fn serde_round_trip() {
        let id = DialogId::RE_ROLL_BLOCK_FOR_TARGETS;
        let json = serde_json::to_string(&id).unwrap();
        let back: DialogId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn get_name_re_roll_is_camel_case() {
        assert_eq!(DialogId::RE_ROLL.get_name(), "reRoll");
    }

    #[test]
    fn for_name_block_roll_round_trips() {
        assert_eq!(DialogId::for_name("blockRoll"), Some(DialogId::BLOCK_ROLL));
    }

    #[test]
    fn variants_are_eq() {
        assert_eq!(DialogId::TOUCHBACK, DialogId::TOUCHBACK);
        assert_ne!(DialogId::TOUCHBACK, DialogId::INTERCEPTION);
    }
}
