use serde::{Deserialize, Serialize};

/// Unique identifier for a Blood Bowl skill (all editions combined).
///
/// Variants correspond 1-to-1 with Java skill class names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SkillId {
    // ── Common (all editions) ───────────────────────────────────────────────
    Block,
    Catch,
    Dauntless,
    DisturbingPresence,
    DivingCatch,
    DumpOff,
    ExtraArms,
    Fend,
    FoulAppearance,
    HailMaryPass,
    Horns,
    JumpUp,
    MovementIncrease,
    Pass,
    Sprint,
    StandFirm,
    StripBall,
    SureHands,
    Tackle,
    Tentacles,
    ThickSkull,
    TwoHeads,
    Wrestle,

    // ── BB2020 & BB2025 skills ──────────────────────────────────────────────
    AnimalSavagery,
    Animosity,
    BallAndChain,
    Bombardier,
    BoneHead,
    Brawler,
    BreakTackle,
    BreatheFire,
    Chainsaw,
    CloudBurster,
    Defensive,
    DirtyPlayer,
    Fumblerooskie,
    HitAndRun,
    HypnoticGaze,
    Leap,
    MightyBlow,
    MonstrousMouth,
    NoHands,
    PassingIncrease,
    PileDriver,
    PilingOn,
    PogoStick,
    ProjectileVomit,
    ReallyStupid,
    Regeneration,
    RightStuff,
    RunningPass,
    Shadowing,
    SideStep,
    SneakyGit,
    Stab,
    StrengthIncrease,
    SureFeet,
    Swarming,
    Swoop,
    VeryLongLegs,

    // ── BB2020 special skills ───────────────────────────────────────────────
    ASneakyPair,
    BlastIt,
    BrutalBlock,
    BurstOfSpeed,
    ConsummateProfessional,
    DwarfenScourge,
    ExcuseMeAreYouAZoat,
    FrenziedRush,
    GhostlyFlames,
    Incorporeal,
    LordOfChaos,
    MasterAssassin,
    MesmerizingDance,
    PumpUpTheCrowd,
    PutridRegurgitation,
    TheBallista,
    ThenIStartedBlastin,
    TwoForOne,
    WhirlingDervish,
    WisdomOfTheWhiteDwarf,
    Yoink,

    // ── Mixed (multiple editions) ──────────────────────────────────────────
    ArmBar,
    BalefulHex,
    Cannoneer,
    IronHardSkin,
    LookIntoMyEyes,
    MyBall,
    PickMeUp,
    SafePass,
    SafePairOfHands,
    Slayer,
    ToxinConnoisseur,
    UnchannelledFury,

    // ── BB2016-only skills ──────────────────────────────────────────────────
    Accurate,
    AlwaysHungry,
    ArmourIncrease,
    BloodLust,
    Claw,
    Decay,
    Disposable,
    DivingTackle,
    FanFavourite,
    Frenzy,
    Grab,
    Guard,
    KickOffReturn,
    KickTeamMate,
    Loner,
    MultipleBlock,
    NervesOfSteel,
    NurglesRot,
    PassBlock,
    PrehensileTail,
    SafeThrow,
    SecretWeapon,
    Stakes,
    StrongArm,
    Stunty,
    TakeRoot,
    ThrowTeamMate,
    Timmmber,
    Titchy,
    WeepingDagger,
    WildAnimal,

    // ── BB2025-only skills ──────────────────────────────────────────────────
    AgilityIncrease,
    BigHand,
    Bullseye,
    Dodge,
    EyeGouge,
    Fumblerooski,
    GiveAndGo,
    Hatred,
    Insignificant,
    Juggernaut,
    Kick,
    Leader,
    LethalFlight,
    LoneFouler,
    NoBall,
    OnTheBall,
    Pogo,
    Pro,
    Punt,
    PutTheBootIn,
    QuickFoul,
    Saboteur,
    Sidestep,
    BlastinSolvesEverything,
    DwarvenScourge,
    KrumpAndSmash,
    MesmerisingDance,
    SlashingNails,
    SteadyFooting,
    TeamCaptain,
    Taunt,
    Unsteady,
    ViolentInnovator,
    WoodlandFury,
    WorkingInTandem,

    // ── Mixed/special star player traits (BB2020 + BB2025) ────────────────────
    AllYouCanEat,
    BeerBarrelBash,
    BlackInk,
    BlindRage,
    BoundingLeap,
    BugmansXXXXXX,
    CatchOfTheDay,
    CrushingBlow,
    Drunkard,
    FuriousOutburst,
    FuryOfTheBloodGod,
    GoredByTheBull,
    HalflingLuck,
    IllBeBack,
    Indomitable,
    Kaboom,
    KeenPlayer,
    KickEmWhileTheyReDown,
    MaximumCarnage,
    OldPro,
    PlagueRidden,
    PrimalSavagery,
    QuickBite,
    RaidingParty,
    Ram,
    Reliable,
    SavageBlow,
    SavageMauling,
    ShotToNothing,
    SneakiestOfTheLot,
    StarOfTheShow,
    StrongPassingGame,
    SwiftAsTheBreeze,
    TastyMorsel,
    TheFlashingBlade,
    ThinkingMansTroll,
    Treacherous,
    Trickster,
    UnstoppableMomentum,
    ViciousVines,
    WatchOut,
}

impl SkillId {
    /// The Java class name used for this skill (matches JSON `class_name` field).
    pub fn class_name(self) -> &'static str {
        match self {
            SkillId::Block => "Block",
            SkillId::Catch => "Catch",
            SkillId::Dauntless => "Dauntless",
            SkillId::DisturbingPresence => "DisturbingPresence",
            SkillId::DivingCatch => "DivingCatch",
            SkillId::DumpOff => "DumpOff",
            SkillId::ExtraArms => "ExtraArms",
            SkillId::Fend => "Fend",
            SkillId::FoulAppearance => "FoulAppearance",
            SkillId::HailMaryPass => "HailMaryPass",
            SkillId::Horns => "Horns",
            SkillId::JumpUp => "JumpUp",
            SkillId::MovementIncrease => "MovementIncrease",
            SkillId::Pass => "Pass",
            SkillId::Sprint => "Sprint",
            SkillId::StandFirm => "StandFirm",
            SkillId::StripBall => "StripBall",
            SkillId::SureHands => "SureHands",
            SkillId::Tackle => "Tackle",
            SkillId::Tentacles => "Tentacles",
            SkillId::ThickSkull => "ThickSkull",
            SkillId::TwoHeads => "TwoHeads",
            SkillId::Wrestle => "Wrestle",
            SkillId::AnimalSavagery => "AnimalSavagery",
            SkillId::Animosity => "Animosity",
            SkillId::BallAndChain => "BallAndChain",
            SkillId::Bombardier => "Bombardier",
            SkillId::BoneHead => "BoneHead",
            SkillId::Brawler => "Brawler",
            SkillId::BreakTackle => "BreakTackle",
            SkillId::BreatheFire => "BreatheFire",
            SkillId::Chainsaw => "Chainsaw",
            SkillId::CloudBurster => "CloudBurster",
            SkillId::Defensive => "Defensive",
            SkillId::DirtyPlayer => "DirtyPlayer",
            SkillId::Fumblerooskie => "Fumblerooskie",
            SkillId::HitAndRun => "HitAndRun",
            SkillId::HypnoticGaze => "HypnoticGaze",
            SkillId::Leap => "Leap",
            SkillId::MightyBlow => "MightyBlow",
            SkillId::MonstrousMouth => "MonstrousMouth",
            SkillId::NoHands => "NoHands",
            SkillId::PassingIncrease => "PassingIncrease",
            SkillId::PileDriver => "PileDriver",
            SkillId::PilingOn => "PilingOn",
            SkillId::PogoStick => "PogoStick",
            SkillId::ProjectileVomit => "ProjectileVomit",
            SkillId::ReallyStupid => "ReallyStupid",
            SkillId::Regeneration => "Regeneration",
            SkillId::RightStuff => "RightStuff",
            SkillId::RunningPass => "RunningPass",
            SkillId::Shadowing => "Shadowing",
            SkillId::SideStep => "SideStep",
            SkillId::SneakyGit => "SneakyGit",
            SkillId::Stab => "Stab",
            SkillId::StrengthIncrease => "StrengthIncrease",
            SkillId::SureFeet => "SureFeet",
            SkillId::Swarming => "Swarming",
            SkillId::Swoop => "Swoop",
            SkillId::VeryLongLegs => "VeryLongLegs",
            SkillId::ASneakyPair => "ASneakyPair",
            SkillId::BlastIt => "BlastIt",
            SkillId::BrutalBlock => "BrutalBlock",
            SkillId::BurstOfSpeed => "BurstOfSpeed",
            SkillId::ConsummateProfessional => "ConsummateProfessional",
            SkillId::DwarfenScourge => "DwarfenScourge",
            SkillId::ExcuseMeAreYouAZoat => "ExcuseMeAreYouAZoat",
            SkillId::FrenziedRush => "FrenziedRush",
            SkillId::GhostlyFlames => "GhostlyFlames",
            SkillId::Incorporeal => "Incorporeal",
            SkillId::LordOfChaos => "LordOfChaos",
            SkillId::MasterAssassin => "MasterAssassin",
            SkillId::MesmerizingDance => "MesmerizingDance",
            SkillId::PumpUpTheCrowd => "PumpUpTheCrowd",
            SkillId::PutridRegurgitation => "PutridRegurgitation",
            SkillId::TheBallista => "TheBallista",
            SkillId::ThenIStartedBlastin => "ThenIStartedBlastin",
            SkillId::TwoForOne => "TwoForOne",
            SkillId::WhirlingDervish => "WhirlingDervish",
            SkillId::WisdomOfTheWhiteDwarf => "WisdomOfTheWhiteDwarf",
            SkillId::Yoink => "Yoink",
            SkillId::Accurate => "Accurate",
            SkillId::AlwaysHungry => "AlwaysHungry",
            SkillId::ArmourIncrease => "ArmourIncrease",
            SkillId::BloodLust => "BloodLust",
            SkillId::Claw => "Claw",
            SkillId::Decay => "Decay",
            SkillId::Disposable => "Disposable",
            SkillId::DivingTackle => "DivingTackle",
            SkillId::FanFavourite => "FanFavourite",
            SkillId::Frenzy => "Frenzy",
            SkillId::Grab => "Grab",
            SkillId::Guard => "Guard",
            SkillId::KickOffReturn => "KickOffReturn",
            SkillId::KickTeamMate => "KickTeamMate",
            SkillId::Loner => "Loner",
            SkillId::MultipleBlock => "MultipleBlock",
            SkillId::NervesOfSteel => "NervesOfSteel",
            SkillId::NurglesRot => "NurglesRot",
            SkillId::PassBlock => "PassBlock",
            SkillId::PrehensileTail => "PrehensileTail",
            SkillId::ArmBar => "ArmBar",
            SkillId::BalefulHex => "BalefulHex",
            SkillId::Cannoneer => "Cannoneer",
            SkillId::LookIntoMyEyes => "LookIntoMyEyes",
            SkillId::IronHardSkin => "IronHardSkin",
            SkillId::MyBall => "MyBall",
            SkillId::PickMeUp => "PickMeUp",
            SkillId::SafePass => "SafePass",
            SkillId::SafePairOfHands => "SafePairOfHands",
            SkillId::Slayer => "Slayer",
            SkillId::ToxinConnoisseur => "ToxinConnoisseur",
            SkillId::UnchannelledFury => "UnchannelledFury",
            SkillId::SafeThrow => "SafeThrow",
            SkillId::SecretWeapon => "SecretWeapon",
            SkillId::Stakes => "Stakes",
            SkillId::StrongArm => "StrongArm",
            SkillId::Stunty => "Stunty",
            SkillId::TakeRoot => "TakeRoot",
            SkillId::ThrowTeamMate => "ThrowTeamMate",
            SkillId::Timmmber => "Timmmber",
            SkillId::Titchy => "Titchy",
            SkillId::WeepingDagger => "WeepingDagger",
            SkillId::WildAnimal => "WildAnimal",
            SkillId::AgilityIncrease => "AgilityIncrease",
            SkillId::BigHand => "BigHand",
            SkillId::Bullseye => "Bullseye",
            SkillId::Dodge => "Dodge",
            SkillId::EyeGouge => "EyeGouge",
            SkillId::Fumblerooski => "Fumblerooski",
            SkillId::GiveAndGo => "GiveAndGo",
            SkillId::Hatred => "Hatred",
            SkillId::Insignificant => "Insignificant",
            SkillId::Juggernaut => "Juggernaut",
            SkillId::Kick => "Kick",
            SkillId::Leader => "Leader",
            SkillId::LethalFlight => "LethalFlight",
            SkillId::LoneFouler => "LoneFouler",
            SkillId::NoBall => "NoBall",
            SkillId::OnTheBall => "OnTheBall",
            SkillId::Pogo => "Pogo",
            SkillId::Pro => "Pro",
            SkillId::Punt => "Punt",
            SkillId::PutTheBootIn => "PutTheBootIn",
            SkillId::QuickFoul => "QuickFoul",
            SkillId::Saboteur => "Saboteur",
            SkillId::Sidestep => "Sidestep",
            SkillId::BlastinSolvesEverything => "BlastinSolvesEverything",
            SkillId::DwarvenScourge => "DwarvenScourge",
            SkillId::KrumpAndSmash => "KrumpAndSmash",
            SkillId::MesmerisingDance => "MesmerisingDance",
            SkillId::SlashingNails => "SlashingNails",
            SkillId::SteadyFooting => "SteadyFooting",
            SkillId::TeamCaptain => "TeamCaptain",
            SkillId::Taunt => "Taunt",
            SkillId::Unsteady => "Unsteady",
            SkillId::ViolentInnovator => "ViolentInnovator",
            SkillId::WoodlandFury => "WoodlandFury",
            SkillId::WorkingInTandem => "WorkingInTandem",
            SkillId::Wrestle => "Wrestle",
            SkillId::AllYouCanEat => "AllYouCanEat",
            SkillId::BeerBarrelBash => "BeerBarrelBash",
            SkillId::BlackInk => "BlackInk",
            SkillId::BlindRage => "BlindRage",
            SkillId::BoundingLeap => "BoundingLeap",
            SkillId::BugmansXXXXXX => "BugmansXXXXXX",
            SkillId::CatchOfTheDay => "CatchOfTheDay",
            SkillId::CrushingBlow => "CrushingBlow",
            SkillId::Drunkard => "Drunkard",
            SkillId::FuriousOutburst => "FuriousOutburst",
            SkillId::FuryOfTheBloodGod => "FuryOfTheBloodGod",
            SkillId::GoredByTheBull => "GoredByTheBull",
            SkillId::HalflingLuck => "HalflingLuck",
            SkillId::IllBeBack => "IllBeBack",
            SkillId::Indomitable => "Indomitable",
            SkillId::Kaboom => "Kaboom",
            SkillId::KeenPlayer => "KeenPlayer",
            SkillId::KickEmWhileTheyReDown => "KickEmWhileTheyReDown",
            SkillId::MaximumCarnage => "MaximumCarnage",
            SkillId::OldPro => "OldPro",
            SkillId::PlagueRidden => "PlagueRidden",
            SkillId::PrimalSavagery => "PrimalSavagery",
            SkillId::QuickBite => "QuickBite",
            SkillId::RaidingParty => "RaidingParty",
            SkillId::Ram => "Ram",
            SkillId::Reliable => "Reliable",
            SkillId::SavageBlow => "SavageBlow",
            SkillId::SavageMauling => "SavageMauling",
            SkillId::ShotToNothing => "ShotToNothing",
            SkillId::SneakiestOfTheLot => "SneakiestOfTheLot",
            SkillId::StarOfTheShow => "StarOfTheShow",
            SkillId::StrongPassingGame => "StrongPassingGame",
            SkillId::SwiftAsTheBreeze => "SwiftAsTheBreeze",
            SkillId::TastyMorsel => "TastyMorsel",
            SkillId::TheFlashingBlade => "TheFlashingBlade",
            SkillId::ThinkingMansTroll => "ThinkingMansTroll",
            SkillId::Treacherous => "Treacherous",
            SkillId::Trickster => "Trickster",
            SkillId::UnstoppableMomentum => "UnstoppableMomentum",
            SkillId::ViciousVines => "ViciousVines",
            SkillId::WatchOut => "WatchOut",
        }
    }

    /// Parse from a Java class name string OR a human-readable skill name.
    ///
    /// Normalizes the input by stripping all non-alphanumeric characters and
    /// lowercasing before matching, so "Secret Weapon", "secret_weapon",
    /// "SecretWeapon", and "secret weapon" all resolve identically.
    pub fn from_class_name(s: &str) -> Option<SkillId> {
        // Exact case-sensitive match first: distinguishes pairs like "SideStep" (BB2020)
        // vs "Sidestep" (BB2025) that normalize to the same lowercase key.
        let exact = match s {
            "SideStep" => return Some(SkillId::SideStep),
            "Sidestep" => return Some(SkillId::Sidestep),
            _ => None::<SkillId>,
        };
        let _ = exact; // suppress warning
        let n: String = s.chars().filter(|c| c.is_alphanumeric()).collect::<String>().to_lowercase();
        let skill = match n.as_str() {
            "accurate" => SkillId::Accurate,
            "agilityincrease" => SkillId::AgilityIncrease,
            "alwayshungry" => SkillId::AlwaysHungry,
            "animalsavagery" => SkillId::AnimalSavagery,
            "animosity" => SkillId::Animosity,
            "armourincrease" => SkillId::ArmourIncrease,
            "asneakypair" => SkillId::ASneakyPair,
            "ballandchain" => SkillId::BallAndChain,
            "bighand" => SkillId::BigHand,
            "blastinsolveseverything" => SkillId::BlastinSolvesEverything,
            "blastit" => SkillId::BlastIt,
            "bloodlust" => SkillId::BloodLust,
            "block" => SkillId::Block,
            "bombardier" => SkillId::Bombardier,
            "bonehead" => SkillId::BoneHead,
            "brawler" => SkillId::Brawler,
            "breaktackle" => SkillId::BreakTackle,
            "breathefire" => SkillId::BreatheFire,
            "brutalblock" => SkillId::BrutalBlock,
            "bullseye" => SkillId::Bullseye,
            "burstofspeed" => SkillId::BurstOfSpeed,
            "catch" => SkillId::Catch,
            "chainsaw" => SkillId::Chainsaw,
            "claw" | "claws" => SkillId::Claw,
            "cloudburster" => SkillId::CloudBurster,
            "consummateprofessional" => SkillId::ConsummateProfessional,
            "dauntless" => SkillId::Dauntless,
            "decay" => SkillId::Decay,
            "defensive" => SkillId::Defensive,
            "dirtyplayer" => SkillId::DirtyPlayer,
            "disposable" => SkillId::Disposable,
            "disturbingpresence" => SkillId::DisturbingPresence,
            "divingcatch" => SkillId::DivingCatch,
            "divingtackle" => SkillId::DivingTackle,
            "dodge" => SkillId::Dodge,
            "dumpoff" => SkillId::DumpOff,
            "dwarfenscourge" => SkillId::DwarfenScourge,
            "dwarvenscourge" => SkillId::DwarvenScourge,
            "excusemeareyouazoat" => SkillId::ExcuseMeAreYouAZoat,
            "extraarms" => SkillId::ExtraArms,
            "eyegouge" => SkillId::EyeGouge,
            "fanfavourite" => SkillId::FanFavourite,
            "fend" => SkillId::Fend,
            "foulappearance" => SkillId::FoulAppearance,
            "frenzy" => SkillId::Frenzy,
            "frenziedrush" => SkillId::FrenziedRush,
            "fumblerooski" => SkillId::Fumblerooski,
            "fumblerooskie" => SkillId::Fumblerooskie,
            "ghostlyflames" => SkillId::GhostlyFlames,
            "giveandgo" => SkillId::GiveAndGo,
            "grab" => SkillId::Grab,
            "guard" => SkillId::Guard,
            "hailmarypass" => SkillId::HailMaryPass,
            "hatred" => SkillId::Hatred,
            "hitandrun" => SkillId::HitAndRun,
            "horns" => SkillId::Horns,
            "hypnoticgaze" => SkillId::HypnoticGaze,
            "incorporeal" => SkillId::Incorporeal,
            "insignificant" => SkillId::Insignificant,
            "juggernaut" => SkillId::Juggernaut,
            "jumpup" => SkillId::JumpUp,
            "kick" => SkillId::Kick,
            "kickoffreturn" => SkillId::KickOffReturn,
            "kickteammate" => SkillId::KickTeamMate,
            "krumpandsmash" => SkillId::KrumpAndSmash,
            "leader" => SkillId::Leader,
            "leap" => SkillId::Leap,
            "lethalflight" => SkillId::LethalFlight,
            "lonefouler" => SkillId::LoneFouler,
            "loner" => SkillId::Loner,
            "lordofchaos" => SkillId::LordOfChaos,
            "masterassassin" => SkillId::MasterAssassin,
            "mesmerizingdance" => SkillId::MesmerizingDance,
            "mesmerisingdance" => SkillId::MesmerisingDance,
            "mightyblow" => SkillId::MightyBlow,
            "monstrousmouth" => SkillId::MonstrousMouth,
            "movementincrease" => SkillId::MovementIncrease,
            "multipleblock" => SkillId::MultipleBlock,
            "nervesofsteel" => SkillId::NervesOfSteel,
            "noball" => SkillId::NoBall,
            "ontheball" => SkillId::OnTheBall,
            "nohands" => SkillId::NoHands,
            "nurglesrot" => SkillId::NurglesRot,
            "pass" => SkillId::Pass,
            "passblock" => SkillId::PassBlock,
            "passingincrease" => SkillId::PassingIncrease,
            "piledriver" => SkillId::PileDriver,
            "pilingon" => SkillId::PilingOn,
            "pogo" => SkillId::Pogo,
            "pogostick" => SkillId::PogoStick,
            "prehensiletail" => SkillId::PrehensileTail,
            "pro" => SkillId::Pro,
            "projectilevomit" => SkillId::ProjectileVomit,
            "pumpupthecrowd" => SkillId::PumpUpTheCrowd,
            "punt" => SkillId::Punt,
            "putridregurgitation" => SkillId::PutridRegurgitation,
            "putthebootin" => SkillId::PutTheBootIn,
            "quickfoul" => SkillId::QuickFoul,
            "reallystupid" => SkillId::ReallyStupid,
            "regeneration" => SkillId::Regeneration,
            "rightstuff" => SkillId::RightStuff,
            "runningpass" => SkillId::RunningPass,
            "saboteur" => SkillId::Saboteur,
            "armbar" => SkillId::ArmBar,
            "balefulhex" => SkillId::BalefulHex,
            "cannoneer" => SkillId::Cannoneer,
            "lookintomyeyes" => SkillId::LookIntoMyEyes,
            "ironhardskin" => SkillId::IronHardSkin,
            "myball" => SkillId::MyBall,
            "pickmeup" => SkillId::PickMeUp,
            "safepass" => SkillId::SafePass,
            "safepairofhands" => SkillId::SafePairOfHands,
            "slayer" => SkillId::Slayer,
            "toxinconnoisseur" => SkillId::ToxinConnoisseur,
            "unchannelledfury" => SkillId::UnchannelledFury,
            "safethrow" => SkillId::SafeThrow,
            "secretweapon" => SkillId::SecretWeapon,
            "shadowing" => SkillId::Shadowing,
            "sidestep" => SkillId::SideStep,
            "slashingnails" => SkillId::SlashingNails,
            "sneakygit" => SkillId::SneakyGit,
            "sprint" => SkillId::Sprint,
            "stab" => SkillId::Stab,
            "stakes" => SkillId::Stakes,
            "standfirm" => SkillId::StandFirm,
            "steadyfooting" => SkillId::SteadyFooting,
            "strengthincrease" => SkillId::StrengthIncrease,
            "stripball" => SkillId::StripBall,
            "strongarm" => SkillId::StrongArm,
            "stunty" => SkillId::Stunty,
            "surefeet" => SkillId::SureFeet,
            "surehands" => SkillId::SureHands,
            "swarming" => SkillId::Swarming,
            "swoop" => SkillId::Swoop,
            "tackle" => SkillId::Tackle,
            "takeroot" => SkillId::TakeRoot,
            "taunt" => SkillId::Taunt,
            "teamcaptain" => SkillId::TeamCaptain,
            "tentacles" => SkillId::Tentacles,
            "theballista" => SkillId::TheBallista,
            "thenistartedblastin" => SkillId::ThenIStartedBlastin,
            "thickskull" => SkillId::ThickSkull,
            "throwteammate" => SkillId::ThrowTeamMate,
            "timmmber" => SkillId::Timmmber,
            "titchy" => SkillId::Titchy,
            "twoforone" => SkillId::TwoForOne,
            "twoheads" => SkillId::TwoHeads,
            "unsteady" => SkillId::Unsteady,
            "verylonglegs" => SkillId::VeryLongLegs,
            "violentinnovator" => SkillId::ViolentInnovator,
            "weepingdagger" => SkillId::WeepingDagger,
            "whirlingdervish" => SkillId::WhirlingDervish,
            "wildanimal" => SkillId::WildAnimal,
            "wisdomofthewhitedwarf" => SkillId::WisdomOfTheWhiteDwarf,
            "woodlandfury" => SkillId::WoodlandFury,
            "yoink" => SkillId::Yoink,
            "workingintandem" => SkillId::WorkingInTandem,
            "wrestle" => SkillId::Wrestle,
            "allyoucaneat" => SkillId::AllYouCanEat,
            "beerbarrelbash" => SkillId::BeerBarrelBash,
            "blackink" => SkillId::BlackInk,
            "blindrage" => SkillId::BlindRage,
            "boundingleap" => SkillId::BoundingLeap,
            "bugmansxxxxxx" => SkillId::BugmansXXXXXX,
            "catchoftheday" => SkillId::CatchOfTheDay,
            "crushingblow" => SkillId::CrushingBlow,
            "drunkard" => SkillId::Drunkard,
            "furiousoutburst" => SkillId::FuriousOutburst,
            "furyofthebloodgod" => SkillId::FuryOfTheBloodGod,
            "goredbythebull" => SkillId::GoredByTheBull,
            "halflingluck" => SkillId::HalflingLuck,
            "illbeback" => SkillId::IllBeBack,
            "indomitable" => SkillId::Indomitable,
            "kaboom" => SkillId::Kaboom,
            "keenplayer" => SkillId::KeenPlayer,
            "kickemwhiletheyredown" => SkillId::KickEmWhileTheyReDown,
            "maximumcarnage" => SkillId::MaximumCarnage,
            "oldpro" => SkillId::OldPro,
            "plagueridden" => SkillId::PlagueRidden,
            "primalsavagery" => SkillId::PrimalSavagery,
            "quickbite" => SkillId::QuickBite,
            "raidingparty" => SkillId::RaidingParty,
            "ram" => SkillId::Ram,
            "reliable" => SkillId::Reliable,
            "savageblow" => SkillId::SavageBlow,
            "savagemauling" => SkillId::SavageMauling,
            "shottonothing" => SkillId::ShotToNothing,
            "sneakiestofthelot" => SkillId::SneakiestOfTheLot,
            "staroftheshow" => SkillId::StarOfTheShow,
            "strongpassinggame" => SkillId::StrongPassingGame,
            "swiftasthebreeze" => SkillId::SwiftAsTheBreeze,
            "tastymorsel" => SkillId::TastyMorsel,
            "theflashingblade" => SkillId::TheFlashingBlade,
            "thinkingmanstroll" => SkillId::ThinkingMansTroll,
            "treacherous" => SkillId::Treacherous,
            "trickster" => SkillId::Trickster,
            "unstoppablemomentum" => SkillId::UnstoppableMomentum,
            "viciousvines" => SkillId::ViciousVines,
            "watchout" => SkillId::WatchOut,

            // ── Human-readable aliases (space/hyphen separated) used in FUMBBL JSON data ──────
            _ => return None,
        };
        Some(skill)
    }

    /// Returns the NamedProperty string keys this skill grants.
    /// 1:1 translation of Skill.getSkillProperties() → SkillId lookup table.
    pub fn properties(self) -> &'static [&'static str] {
        match self {
            SkillId::SteadyFooting => &["canAvoidFallingDown"],
            SkillId::TakeRoot => &["becomesImmovable"],
            SkillId::Sprint => &["canMakeAnExtraGfi"],
            SkillId::SureFeet => &["canMakeAnExtraGfiOnce"],
            SkillId::Block => &["preventFallOnBothDown"],
            SkillId::Dodge => &["ignoreDefenderStumblesResult", "canRerollDodge"],
            SkillId::Fend => &["preventOpponentFollowingUp"],
            SkillId::StandFirm => &["canRefuseToBePushed"],
            SkillId::SideStep => &["canChooseOwnPushedBackSquare"],
            SkillId::Sidestep => &["canChooseOwnPushedBackSquare"],
            SkillId::Shadowing => &["canFollowPlayerLeavingTacklezones"],
            SkillId::HypnoticGaze => &["inflictsConfusion", "canGazeDuringMove"],
            SkillId::Leap => &["canLeap"],
            SkillId::PogoStick => &[
                "canLeap",
                "ignoreTacklezonesWhenJumping",
                "failedRushForJumpAlwaysLandsInTargetSquare",
            ],
            SkillId::Pogo => &[
                "canLeap",
                "ignoreTacklezonesWhenJumping",
                "failedRushForJumpAlwaysLandsInTargetSquare",
            ],
            SkillId::Juggernaut => &["canConvertBothDownToPush"],
            SkillId::Frenzy => &["forceFollowup", "forceSecondBlock"],
            SkillId::Guard => &["assistsBlocksInTacklezones", "assistsFoulsInTacklezones"],
            SkillId::DivingTackle => &["canAttemptToTackleDodgingPlayer"],
            SkillId::Tentacles => &["canHoldPlayersLeavingTacklezones"],
            SkillId::AlwaysHungry => &["mightEatPlayerToThrow"],
            SkillId::BoneHead => &["appliesConfusion"],
            SkillId::ReallyStupid => &["appliesConfusion", "needsToRollHighToAvoidConfusion"],
            SkillId::MightyBlow => &["affectsEitherArmourOrInjuryOnBlock"],
            SkillId::DirtyPlayer => &["affectsEitherArmourOrInjuryOnFoul"],
            SkillId::Stab => &[
                "canPerformArmourRollInsteadOfBlock",
                "providesBlockAlternative",
                "providesStabBlockAlternative",
            ],
            SkillId::Chainsaw => &[
                "makesStrengthTestObsolete",
                "blocksLikeChainsaw",
                "needsNoDiceDecorations",
                "providesChainsawBlockAlternative",
                "providesChainsawFoulingAlternative",
            ],
            SkillId::Claw => &["reducesArmourToFixedValue"],
            SkillId::ThickSkull => &["convertKOToStunOn8"],
            SkillId::AnimalSavagery => &[
                "enableStandUpAndEndBlitzAction",
                "needsToRollForActionBlockingIsEasier",
            ],
            SkillId::HitAndRun => &["goForItAfterBlock", "canMoveAfterBlock"],
            SkillId::QuickFoul => &["canMoveAfterFoul"],
            SkillId::Pro => &[
                "canChooseToIgnoreRushModifierAfterRoll",
                "canChooseToIgnoreDodgeModifierAfterRoll",
                "canRerollOncePerTurn",
            ],
            SkillId::MultipleBlock => &[
                "providesMultipleBlockAlternative",
                "canBlockMoreThanOnce",
                "canBlockTwoAtOnce",
            ],
            SkillId::Dauntless => &["canRollToMatchOpponentsStrength"],
            SkillId::DisturbingPresence => &["inflictsDisturbingPresence"],
            SkillId::FoulAppearance => &["inflictsFoulAppearance"],
            SkillId::PrehensileTail => &["canHoldPlayersLeavingTacklezones"],
            SkillId::Tackle => &["cancelsDodge"],
            SkillId::Wrestle => &["canChooseToFallDownForBothDown"],
            SkillId::Swoop => &["ttmScattersInSingleDirection"],
            SkillId::KickTeamMate => &["canKickTeamMates"],
            SkillId::ThrowTeamMate => &["canThrowTeamMates"],
            SkillId::RightStuff => &["canBeThrown"],
            SkillId::WildAnimal => &["needsToRollForAction"],
            SkillId::Loner => &["needsToRollForTeamReroll"],
            SkillId::Decay => &["decaysAfterInjury"],
            SkillId::Regeneration => &["preventRaiseFromDead", "canRollToSaveFromInjury"],
            SkillId::GiveAndGo => &["canMoveAfterQuickPass", "canMoveAfterHandOff"],
            SkillId::RunningPass => &["canMoveAfterQuickPass"],
            SkillId::DivingCatch => &["canAttemptCatchInAdjacentSquares"],
            SkillId::NoHands => &["preventCatch"],
            _ => &[],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn class_name_round_trip() {
        let cases = [SkillId::Block, SkillId::Dodge, SkillId::MightyBlow, SkillId::Wrestle];
        for id in cases {
            let name = id.class_name();
            assert_eq!(SkillId::from_class_name(name), Some(id), "round-trip failed for {name}");
        }
    }

    #[test]
    fn unknown_class_name_returns_none() {
        assert_eq!(SkillId::from_class_name("NonExistentSkill"), None);
    }

    #[test]
    fn properties_steady_footing() {
        assert_eq!(SkillId::SteadyFooting.properties(), &["canAvoidFallingDown"]);
    }

    #[test]
    fn properties_dodge_has_two() {
        let props = SkillId::Dodge.properties();
        assert!(props.contains(&"ignoreDefenderStumblesResult"));
        assert!(props.contains(&"canRerollDodge"));
    }

    #[test]
    fn properties_block() {
        assert!(SkillId::Block.properties().contains(&"preventFallOnBothDown"));
    }

    #[test]
    fn properties_leap() {
        assert!(SkillId::Leap.properties().contains(&"canLeap"));
    }

    #[test]
    fn properties_pogo_includes_leap() {
        assert!(SkillId::PogoStick.properties().contains(&"canLeap"));
    }

    #[test]
    fn properties_unknown_skill_returns_empty() {
        assert_eq!(SkillId::Kick.properties(), &[] as &[&str]);
    }

    #[test]
    fn properties_chainsaw_has_five() {
        assert_eq!(SkillId::Chainsaw.properties().len(), 5);
    }
}
