use serde::{Deserialize, Serialize};

/// Unique identifier for a Blood Bowl skill (all editions combined).
///
/// Variants correspond 1-to-1 with Java skill class names.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SkillId {
    // ── Common (all editions) ───────────────────────────────────────────────
    Block,
    Catch,
    Dauntless,
    DisturbingPresence,
    DivingCatch,
    DumpOff,
    ExtraArms,
    Fend,
    FoulAppearance,
    HailMaryPass,
    Horns,
    JumpUp,
    MovementIncrease,
    Pass,
    Sprint,
    StandFirm,
    StripBall,
    SureHands,
    Tackle,
    Tentacles,
    ThickSkull,
    TwoHeads,
    Wrestle,

    // ── BB2020 & BB2025 skills ──────────────────────────────────────────────
    AnimalSavagery,
    Animosity,
    BallAndChain,
    Bombardier,
    BoneHead,
    Brawler,
    BreakTackle,
    BreatheFire,
    Chainsaw,
    CloudBurster,
    Defensive,
    DirtyPlayer,
    Fumblerooskie,
    HitAndRun,
    HypnoticGaze,
    Leap,
    MightyBlow,
    MonstrousMouth,
    NoHands,
    PassingIncrease,
    PileDriver,
    PilingOn,
    PogoStick,
    ProjectileVomit,
    ReallyStupid,
    Regeneration,
    RightStuff,
    RunningPass,
    Shadowing,
    SideStep,
    SneakyGit,
    Stab,
    StrengthIncrease,
    SureFeet,
    Swarming,
    Swoop,
    VeryLongLegs,

    // ── BB2020 special skills ───────────────────────────────────────────────
    ASneakyPair,
    BlastIt,
    BrutalBlock,
    BurstOfSpeed,
    ConsummateProfessional,
    DwarfenScourge,
    ExcuseMeAreYouAZoat,
    FrenziedRush,
    GhostlyFlames,
    Incorporeal,
    LordOfChaos,
    MasterAssassin,
    MesmerizingDance,
    PumpUpTheCrowd,
    PutridRegurgitation,
    TheBallista,
    ThenIStartedBlastin,
    TwoForOne,
    WhirlingDervish,
    WisdomOfTheWhiteDwarf,
    Yoink,

    // ── Mixed (multiple editions) ──────────────────────────────────────────
    ArmBar,
    BalefulHex,
    Cannoneer,
    IronHardSkin,
    LookIntoMyEyes,
    MyBall,
    PickMeUp,
    SafePass,
    SafePairOfHands,
    Slayer,
    ToxinConnoisseur,
    UnchannelledFury,

    // ── BB2016-only skills ──────────────────────────────────────────────────
    Accurate,
    AlwaysHungry,
    ArmourIncrease,
    BloodLust,
    Claw,
    Decay,
    Disposable,
    DivingTackle,
    FanFavourite,
    Frenzy,
    Grab,
    Guard,
    KickOffReturn,
    KickTeamMate,
    Loner,
    MultipleBlock,
    NervesOfSteel,
    NurglesRot,
    PassBlock,
    PrehensileTail,
    SafeThrow,
    SecretWeapon,
    Stakes,
    StrongArm,
    Stunty,
    TakeRoot,
    ThrowTeamMate,
    Timmmber,
    Titchy,
    WeepingDagger,
    WildAnimal,

    // ── BB2025-only skills ──────────────────────────────────────────────────
    AgilityIncrease,
    BigHand,
    Bullseye,
    Dodge,
    EyeGouge,
    Fumblerooski,
    GiveAndGo,
    Hatred,
    Insignificant,
    Juggernaut,
    Kick,
    Leader,
    LethalFlight,
    LoneFouler,
    NoBall,
    OnTheBall,
    Pogo,
    Pro,
    Punt,
    PutTheBootIn,
    QuickFoul,
    Saboteur,
    Sidestep,
    BlastinSolvesEverything,
    DwarvenScourge,
    KrumpAndSmash,
    MesmerisingDance,
    SlashingNails,
    SteadyFooting,
    TeamCaptain,
    Taunt,
    Unsteady,
    ViolentInnovator,
    WoodlandFury,
    WorkingInTandem,

    // ── Mixed/special star player traits (BB2020 + BB2025) ────────────────────
    AllYouCanEat,
    BeerBarrelBash,
    BlackInk,
    BlindRage,
    BoundingLeap,
    BugmansXXXXXX,
    CatchOfTheDay,
    CrushingBlow,
    Drunkard,
    FuriousOutburst,
    FuryOfTheBloodGod,
    GoredByTheBull,
    HalflingLuck,
    IllBeBack,
    Indomitable,
    Kaboom,
    KeenPlayer,
    KickEmWhileTheyReDown,
    MaximumCarnage,
    OldPro,
    PlagueRidden,
    PrimalSavagery,
    QuickBite,
    RaidingParty,
    Ram,
    Reliable,
    SavageBlow,
    SavageMauling,
    ShotToNothing,
    SneakiestOfTheLot,
    StarOfTheShow,
    StrongPassingGame,
    SwiftAsTheBreeze,
    TastyMorsel,
    TheFlashingBlade,
    ThinkingMansTroll,
    Treacherous,
    Trickster,
    UnstoppableMomentum,
    ViciousVines,
    WatchOut,
}

impl SkillId {
    /// The Java class name used for this skill (matches JSON `class_name` field).
    pub fn class_name(self) -> &'static str {
        match self {
            SkillId::Block => "Block",
            SkillId::Catch => "Catch",
            SkillId::Dauntless => "Dauntless",
            SkillId::DisturbingPresence => "DisturbingPresence",
            SkillId::DivingCatch => "DivingCatch",
            SkillId::DumpOff => "DumpOff",
            SkillId::ExtraArms => "ExtraArms",
            SkillId::Fend => "Fend",
            SkillId::FoulAppearance => "FoulAppearance",
            SkillId::HailMaryPass => "HailMaryPass",
            SkillId::Horns => "Horns",
            SkillId::JumpUp => "JumpUp",
            SkillId::MovementIncrease => "MovementIncrease",
            SkillId::Pass => "Pass",
            SkillId::Sprint => "Sprint",
            SkillId::StandFirm => "StandFirm",
            SkillId::StripBall => "StripBall",
            SkillId::SureHands => "SureHands",
            SkillId::Tackle => "Tackle",
            SkillId::Tentacles => "Tentacles",
            SkillId::ThickSkull => "ThickSkull",
            SkillId::TwoHeads => "TwoHeads",
            SkillId::Wrestle => "Wrestle",
            SkillId::AnimalSavagery => "AnimalSavagery",
            SkillId::Animosity => "Animosity",
            SkillId::BallAndChain => "BallAndChain",
            SkillId::Bombardier => "Bombardier",
            SkillId::BoneHead => "BoneHead",
            SkillId::Brawler => "Brawler",
            SkillId::BreakTackle => "BreakTackle",
            SkillId::BreatheFire => "BreatheFire",
            SkillId::Chainsaw => "Chainsaw",
            SkillId::CloudBurster => "CloudBurster",
            SkillId::Defensive => "Defensive",
            SkillId::DirtyPlayer => "DirtyPlayer",
            SkillId::Fumblerooskie => "Fumblerooskie",
            SkillId::HitAndRun => "HitAndRun",
            SkillId::HypnoticGaze => "HypnoticGaze",
            SkillId::Leap => "Leap",
            SkillId::MightyBlow => "MightyBlow",
            SkillId::MonstrousMouth => "MonstrousMouth",
            SkillId::NoHands => "NoHands",
            SkillId::PassingIncrease => "PassingIncrease",
            SkillId::PileDriver => "PileDriver",
            SkillId::PilingOn => "PilingOn",
            SkillId::PogoStick => "PogoStick",
            SkillId::ProjectileVomit => "ProjectileVomit",
            SkillId::ReallyStupid => "ReallyStupid",
            SkillId::Regeneration => "Regeneration",
            SkillId::RightStuff => "RightStuff",
            SkillId::RunningPass => "RunningPass",
            SkillId::Shadowing => "Shadowing",
            SkillId::SideStep => "SideStep",
            SkillId::SneakyGit => "SneakyGit",
            SkillId::Stab => "Stab",
            SkillId::StrengthIncrease => "StrengthIncrease",
            SkillId::SureFeet => "SureFeet",
            SkillId::Swarming => "Swarming",
            SkillId::Swoop => "Swoop",
            SkillId::VeryLongLegs => "VeryLongLegs",
            SkillId::ASneakyPair => "ASneakyPair",
            SkillId::BlastIt => "BlastIt",
            SkillId::BrutalBlock => "BrutalBlock",
            SkillId::BurstOfSpeed => "BurstOfSpeed",
            SkillId::ConsummateProfessional => "ConsummateProfessional",
            SkillId::DwarfenScourge => "DwarfenScourge",
            SkillId::ExcuseMeAreYouAZoat => "ExcuseMeAreYouAZoat",
            SkillId::FrenziedRush => "FrenziedRush",
            SkillId::GhostlyFlames => "GhostlyFlames",
            SkillId::Incorporeal => "Incorporeal",
            SkillId::LordOfChaos => "LordOfChaos",
            SkillId::MasterAssassin => "MasterAssassin",
            SkillId::MesmerizingDance => "MesmerizingDance",
            SkillId::PumpUpTheCrowd => "PumpUpTheCrowd",
            SkillId::PutridRegurgitation => "PutridRegurgitation",
            SkillId::TheBallista => "TheBallista",
            SkillId::ThenIStartedBlastin => "ThenIStartedBlastin",
            SkillId::TwoForOne => "TwoForOne",
            SkillId::WhirlingDervish => "WhirlingDervish",
            SkillId::WisdomOfTheWhiteDwarf => "WisdomOfTheWhiteDwarf",
            SkillId::Yoink => "Yoink",
            SkillId::Accurate => "Accurate",
            SkillId::AlwaysHungry => "AlwaysHungry",
            SkillId::ArmourIncrease => "ArmourIncrease",
            SkillId::BloodLust => "BloodLust",
            SkillId::Claw => "Claw",
            SkillId::Decay => "Decay",
            SkillId::Disposable => "Disposable",
            SkillId::DivingTackle => "DivingTackle",
            SkillId::FanFavourite => "FanFavourite",
            SkillId::Frenzy => "Frenzy",
            SkillId::Grab => "Grab",
            SkillId::Guard => "Guard",
            SkillId::KickOffReturn => "KickOffReturn",
            SkillId::KickTeamMate => "KickTeamMate",
            SkillId::Loner => "Loner",
            SkillId::MultipleBlock => "MultipleBlock",
            SkillId::NervesOfSteel => "NervesOfSteel",
            SkillId::NurglesRot => "NurglesRot",
            SkillId::PassBlock => "PassBlock",
            SkillId::PrehensileTail => "PrehensileTail",
            SkillId::ArmBar => "ArmBar",
            SkillId::BalefulHex => "BalefulHex",
            SkillId::Cannoneer => "Cannoneer",
            SkillId::LookIntoMyEyes => "LookIntoMyEyes",
            SkillId::IronHardSkin => "IronHardSkin",
            SkillId::MyBall => "MyBall",
            SkillId::PickMeUp => "PickMeUp",
            SkillId::SafePass => "SafePass",
            SkillId::SafePairOfHands => "SafePairOfHands",
            SkillId::Slayer => "Slayer",
            SkillId::ToxinConnoisseur => "ToxinConnoisseur",
            SkillId::UnchannelledFury => "UnchannelledFury",
            SkillId::SafeThrow => "SafeThrow",
            SkillId::SecretWeapon => "SecretWeapon",
            SkillId::Stakes => "Stakes",
            SkillId::StrongArm => "StrongArm",
            SkillId::Stunty => "Stunty",
            SkillId::TakeRoot => "TakeRoot",
            SkillId::ThrowTeamMate => "ThrowTeamMate",
            SkillId::Timmmber => "Timmmber",
            SkillId::Titchy => "Titchy",
            SkillId::WeepingDagger => "WeepingDagger",
            SkillId::WildAnimal => "WildAnimal",
            SkillId::AgilityIncrease => "AgilityIncrease",
            SkillId::BigHand => "BigHand",
            SkillId::Bullseye => "Bullseye",
            SkillId::Dodge => "Dodge",
            SkillId::EyeGouge => "EyeGouge",
            SkillId::Fumblerooski => "Fumblerooski",
            SkillId::GiveAndGo => "GiveAndGo",
            SkillId::Hatred => "Hatred",
            SkillId::Insignificant => "Insignificant",
            SkillId::Juggernaut => "Juggernaut",
            SkillId::Kick => "Kick",
            SkillId::Leader => "Leader",
            SkillId::LethalFlight => "LethalFlight",
            SkillId::LoneFouler => "LoneFouler",
            SkillId::NoBall => "NoBall",
            SkillId::OnTheBall => "OnTheBall",
            SkillId::Pogo => "Pogo",
            SkillId::Pro => "Pro",
            SkillId::Punt => "Punt",
            SkillId::PutTheBootIn => "PutTheBootIn",
            SkillId::QuickFoul => "QuickFoul",
            SkillId::Saboteur => "Saboteur",
            SkillId::Sidestep => "Sidestep",
            SkillId::BlastinSolvesEverything => "BlastinSolvesEverything",
            SkillId::DwarvenScourge => "DwarvenScourge",
            SkillId::KrumpAndSmash => "KrumpAndSmash",
            SkillId::MesmerisingDance => "MesmerisingDance",
            SkillId::SlashingNails => "SlashingNails",
            SkillId::SteadyFooting => "SteadyFooting",
            SkillId::TeamCaptain => "TeamCaptain",
            SkillId::Taunt => "Taunt",
            SkillId::Unsteady => "Unsteady",
            SkillId::ViolentInnovator => "ViolentInnovator",
            SkillId::WoodlandFury => "WoodlandFury",
            SkillId::WorkingInTandem => "WorkingInTandem",
            SkillId::Wrestle => "Wrestle",
            SkillId::AllYouCanEat => "AllYouCanEat",
            SkillId::BeerBarrelBash => "BeerBarrelBash",
            SkillId::BlackInk => "BlackInk",
            SkillId::BlindRage => "BlindRage",
            SkillId::BoundingLeap => "BoundingLeap",
            SkillId::BugmansXXXXXX => "BugmansXXXXXX",
            SkillId::CatchOfTheDay => "CatchOfTheDay",
            SkillId::CrushingBlow => "CrushingBlow",
            SkillId::Drunkard => "Drunkard",
            SkillId::FuriousOutburst => "FuriousOutburst",
            SkillId::FuryOfTheBloodGod => "FuryOfTheBloodGod",
            SkillId::GoredByTheBull => "GoredByTheBull",
            SkillId::HalflingLuck => "HalflingLuck",
            SkillId::IllBeBack => "IllBeBack",
            SkillId::Indomitable => "Indomitable",
            SkillId::Kaboom => "Kaboom",
            SkillId::KeenPlayer => "KeenPlayer",
            SkillId::KickEmWhileTheyReDown => "KickEmWhileTheyReDown",
            SkillId::MaximumCarnage => "MaximumCarnage",
            SkillId::OldPro => "OldPro",
            SkillId::PlagueRidden => "PlagueRidden",
            SkillId::PrimalSavagery => "PrimalSavagery",
            SkillId::QuickBite => "QuickBite",
            SkillId::RaidingParty => "RaidingParty",
            SkillId::Ram => "Ram",
            SkillId::Reliable => "Reliable",
            SkillId::SavageBlow => "SavageBlow",
            SkillId::SavageMauling => "SavageMauling",
            SkillId::ShotToNothing => "ShotToNothing",
            SkillId::SneakiestOfTheLot => "SneakiestOfTheLot",
            SkillId::StarOfTheShow => "StarOfTheShow",
            SkillId::StrongPassingGame => "StrongPassingGame",
            SkillId::SwiftAsTheBreeze => "SwiftAsTheBreeze",
            SkillId::TastyMorsel => "TastyMorsel",
            SkillId::TheFlashingBlade => "TheFlashingBlade",
            SkillId::ThinkingMansTroll => "ThinkingMansTroll",
            SkillId::Treacherous => "Treacherous",
            SkillId::Trickster => "Trickster",
            SkillId::UnstoppableMomentum => "UnstoppableMomentum",
            SkillId::ViciousVines => "ViciousVines",
            SkillId::WatchOut => "WatchOut",
        }
    }

    /// Parse from a Java class name string.
    pub fn from_class_name(s: &str) -> Option<SkillId> {
        let skill = match s {
            "Accurate" => SkillId::Accurate,
            "AgilityIncrease" => SkillId::AgilityIncrease,
            "AlwaysHungry" => SkillId::AlwaysHungry,
            "AnimalSavagery" => SkillId::AnimalSavagery,
            "Animosity" => SkillId::Animosity,
            "ArmourIncrease" => SkillId::ArmourIncrease,
            "ASneakyPair" => SkillId::ASneakyPair,
            "BallAndChain" => SkillId::BallAndChain,
            "BigHand" => SkillId::BigHand,
            "BlastinSolvesEverything" => SkillId::BlastinSolvesEverything,
            "BlastIt" => SkillId::BlastIt,
            "BloodLust" => SkillId::BloodLust,
            "Block" => SkillId::Block,
            "Bombardier" => SkillId::Bombardier,
            "BoneHead" => SkillId::BoneHead,
            "Brawler" => SkillId::Brawler,
            "BreakTackle" => SkillId::BreakTackle,
            "BreatheFire" => SkillId::BreatheFire,
            "BrutalBlock" => SkillId::BrutalBlock,
            "Bullseye" => SkillId::Bullseye,
            "BurstOfSpeed" => SkillId::BurstOfSpeed,
            "Catch" => SkillId::Catch,
            "Chainsaw" => SkillId::Chainsaw,
            "Claw" | "Claws" => SkillId::Claw,
            "CloudBurster" => SkillId::CloudBurster,
            "ConsummateProfessional" => SkillId::ConsummateProfessional,
            "Dauntless" => SkillId::Dauntless,
            "Decay" => SkillId::Decay,
            "Defensive" => SkillId::Defensive,
            "DirtyPlayer" => SkillId::DirtyPlayer,
            "Disposable" => SkillId::Disposable,
            "DisturbingPresence" => SkillId::DisturbingPresence,
            "DivingCatch" => SkillId::DivingCatch,
            "DivingTackle" => SkillId::DivingTackle,
            "Dodge" => SkillId::Dodge,
            "DumpOff" => SkillId::DumpOff,
            "DwarfenScourge" => SkillId::DwarfenScourge,
            "DwarvenScourge" => SkillId::DwarvenScourge,
            "ExcuseMeAreYouAZoat" => SkillId::ExcuseMeAreYouAZoat,
            "ExtraArms" => SkillId::ExtraArms,
            "EyeGouge" => SkillId::EyeGouge,
            "FanFavourite" => SkillId::FanFavourite,
            "Fend" => SkillId::Fend,
            "FoulAppearance" => SkillId::FoulAppearance,
            "Frenzy" => SkillId::Frenzy,
            "FrenziedRush" => SkillId::FrenziedRush,
            "Fumblerooski" => SkillId::Fumblerooski,
            "Fumblerooskie" => SkillId::Fumblerooskie,
            "GhostlyFlames" => SkillId::GhostlyFlames,
            "GiveAndGo" => SkillId::GiveAndGo,
            "Grab" => SkillId::Grab,
            "Guard" => SkillId::Guard,
            "HailMaryPass" => SkillId::HailMaryPass,
            "Hatred" => SkillId::Hatred,
            "HitAndRun" => SkillId::HitAndRun,
            "Horns" => SkillId::Horns,
            "HypnoticGaze" => SkillId::HypnoticGaze,
            "Incorporeal" => SkillId::Incorporeal,
            "Insignificant" => SkillId::Insignificant,
            "Juggernaut" => SkillId::Juggernaut,
            "JumpUp" => SkillId::JumpUp,
            "Kick" => SkillId::Kick,
            "KickOffReturn" => SkillId::KickOffReturn,
            "KickTeamMate" => SkillId::KickTeamMate,
            "KrumpAndSmash" => SkillId::KrumpAndSmash,
            "Leader" => SkillId::Leader,
            "Leap" => SkillId::Leap,
            "LethalFlight" => SkillId::LethalFlight,
            "LoneFouler" => SkillId::LoneFouler,
            "Loner" => SkillId::Loner,
            "LordOfChaos" => SkillId::LordOfChaos,
            "MasterAssassin" => SkillId::MasterAssassin,
            "MesmerizingDance" => SkillId::MesmerizingDance,
            "MesmerisingDance" => SkillId::MesmerisingDance,
            "MightyBlow" => SkillId::MightyBlow,
            "MonstrousMouth" => SkillId::MonstrousMouth,
            "MovementIncrease" => SkillId::MovementIncrease,
            "MultipleBlock" => SkillId::MultipleBlock,
            "NervesOfSteel" => SkillId::NervesOfSteel,
            "NoBall" => SkillId::NoBall,
            "OnTheBall" => SkillId::OnTheBall,
            "NoHands" => SkillId::NoHands,
            "NurglesRot" => SkillId::NurglesRot,
            "Pass" => SkillId::Pass,
            "PassBlock" => SkillId::PassBlock,
            "PassingIncrease" => SkillId::PassingIncrease,
            "PileDriver" => SkillId::PileDriver,
            "PilingOn" => SkillId::PilingOn,
            "Pogo" => SkillId::Pogo,
            "PogoStick" => SkillId::PogoStick,
            "PrehensileTail" => SkillId::PrehensileTail,
            "Pro" => SkillId::Pro,
            "ProjectileVomit" => SkillId::ProjectileVomit,
            "PumpUpTheCrowd" => SkillId::PumpUpTheCrowd,
            "Punt" => SkillId::Punt,
            "PutridRegurgitation" => SkillId::PutridRegurgitation,
            "PutTheBootIn" => SkillId::PutTheBootIn,
            "QuickFoul" => SkillId::QuickFoul,
            "ReallyStupid" => SkillId::ReallyStupid,
            "Regeneration" => SkillId::Regeneration,
            "RightStuff" => SkillId::RightStuff,
            "RunningPass" => SkillId::RunningPass,
            "Saboteur" => SkillId::Saboteur,
            "ArmBar" => SkillId::ArmBar,
            "BalefulHex" => SkillId::BalefulHex,
            "Cannoneer" => SkillId::Cannoneer,
            "LookIntoMyEyes" => SkillId::LookIntoMyEyes,
            "IronHardSkin" => SkillId::IronHardSkin,
            "MyBall" => SkillId::MyBall,
            "PickMeUp" => SkillId::PickMeUp,
            "SafePass" => SkillId::SafePass,
            "SafePairOfHands" => SkillId::SafePairOfHands,
            "Slayer" => SkillId::Slayer,
            "ToxinConnoisseur" => SkillId::ToxinConnoisseur,
            "UnchannelledFury" => SkillId::UnchannelledFury,
            "SafeThrow" => SkillId::SafeThrow,
            "SecretWeapon" => SkillId::SecretWeapon,
            "Shadowing" => SkillId::Shadowing,
            "SideStep" => SkillId::SideStep,
            "Sidestep" => SkillId::Sidestep,
            "SlashingNails" => SkillId::SlashingNails,
            "SneakyGit" => SkillId::SneakyGit,
            "Sprint" => SkillId::Sprint,
            "Stab" => SkillId::Stab,
            "Stakes" => SkillId::Stakes,
            "StandFirm" => SkillId::StandFirm,
            "SteadyFooting" => SkillId::SteadyFooting,
            "StrengthIncrease" => SkillId::StrengthIncrease,
            "StripBall" => SkillId::StripBall,
            "StrongArm" => SkillId::StrongArm,
            "Stunty" => SkillId::Stunty,
            "SureFeet" => SkillId::SureFeet,
            "SureHands" => SkillId::SureHands,
            "Swarming" => SkillId::Swarming,
            "Swoop" => SkillId::Swoop,
            "Tackle" => SkillId::Tackle,
            "TakeRoot" => SkillId::TakeRoot,
            "Taunt" => SkillId::Taunt,
            "TeamCaptain" => SkillId::TeamCaptain,
            "Tentacles" => SkillId::Tentacles,
            "TheBallista" => SkillId::TheBallista,
            "ThenIStartedBlastin" => SkillId::ThenIStartedBlastin,
            "ThickSkull" => SkillId::ThickSkull,
            "ThrowTeamMate" => SkillId::ThrowTeamMate,
            "Timmmber" => SkillId::Timmmber,
            "Titchy" => SkillId::Titchy,
            "TwoForOne" => SkillId::TwoForOne,
            "TwoHeads" => SkillId::TwoHeads,
            "Unsteady" => SkillId::Unsteady,
            "VeryLongLegs" => SkillId::VeryLongLegs,
            "ViolentInnovator" => SkillId::ViolentInnovator,
            "WeepingDagger" => SkillId::WeepingDagger,
            "WhirlingDervish" => SkillId::WhirlingDervish,
            "WildAnimal" => SkillId::WildAnimal,
            "WisdomOfTheWhiteDwarf" => SkillId::WisdomOfTheWhiteDwarf,
            "WoodlandFury" => SkillId::WoodlandFury,
            "Yoink" | "Yoink!" => SkillId::Yoink,
            "WorkingInTandem" => SkillId::WorkingInTandem,
            "Wrestle" => SkillId::Wrestle,
            "AllYouCanEat" => SkillId::AllYouCanEat,
            "BeerBarrelBash" => SkillId::BeerBarrelBash,
            "BlackInk" => SkillId::BlackInk,
            "BlindRage" => SkillId::BlindRage,
            "BoundingLeap" => SkillId::BoundingLeap,
            "BugmansXXXXXX" => SkillId::BugmansXXXXXX,
            "CatchOfTheDay" => SkillId::CatchOfTheDay,
            "CrushingBlow" => SkillId::CrushingBlow,
            "Drunkard" => SkillId::Drunkard,
            "FuriousOutburst" => SkillId::FuriousOutburst,
            "FuryOfTheBloodGod" => SkillId::FuryOfTheBloodGod,
            "GoredByTheBull" => SkillId::GoredByTheBull,
            "HalflingLuck" => SkillId::HalflingLuck,
            "IllBeBack" => SkillId::IllBeBack,
            "Indomitable" => SkillId::Indomitable,
            "Kaboom" => SkillId::Kaboom,
            "KeenPlayer" => SkillId::KeenPlayer,
            "KickEmWhileTheyReDown" => SkillId::KickEmWhileTheyReDown,
            "MaximumCarnage" => SkillId::MaximumCarnage,
            "OldPro" => SkillId::OldPro,
            "PlagueRidden" => SkillId::PlagueRidden,
            "PrimalSavagery" => SkillId::PrimalSavagery,
            "QuickBite" => SkillId::QuickBite,
            "RaidingParty" => SkillId::RaidingParty,
            "Ram" => SkillId::Ram,
            "Reliable" => SkillId::Reliable,
            "SavageBlow" => SkillId::SavageBlow,
            "SavageMauling" => SkillId::SavageMauling,
            "ShotToNothing" => SkillId::ShotToNothing,
            "SneakiestOfTheLot" => SkillId::SneakiestOfTheLot,
            "StarOfTheShow" => SkillId::StarOfTheShow,
            "StrongPassingGame" => SkillId::StrongPassingGame,
            "SwiftAsTheBreeze" => SkillId::SwiftAsTheBreeze,
            "TastyMorsel" => SkillId::TastyMorsel,
            "TheFlashingBlade" => SkillId::TheFlashingBlade,
            "ThinkingMansTroll" => SkillId::ThinkingMansTroll,
            "Treacherous" => SkillId::Treacherous,
            "Trickster" => SkillId::Trickster,
            "UnstoppableMomentum" => SkillId::UnstoppableMomentum,
            "ViciousVines" => SkillId::ViciousVines,
            "WatchOut" => SkillId::WatchOut,
            _ => return None,
        };
        Some(skill)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn class_name_round_trip() {
        let cases = [SkillId::Block, SkillId::Dodge, SkillId::MightyBlow, SkillId::Wrestle];
        for id in cases {
            let name = id.class_name();
            assert_eq!(SkillId::from_class_name(name), Some(id), "round-trip failed for {name}");
        }
    }

    #[test]
    fn unknown_class_name_returns_none() {
        assert_eq!(SkillId::from_class_name("NonExistentSkill"), None);
    }
}
