//! 1:1 translation of `java.util.Random` and `java.util.Collections.shuffle`.
//!
//! # Why this exists
//!
//! Several Java engine sites pick an element with the ONE-ARGUMENT
//! `Collections.shuffle(list)`, which uses `java.util.Collections`' private shared
//! `Random` — **not** the game's seeded `DiceRoller`:
//!
//! * `bb2020/StepApplyKickoffResult.handleCheeringFans` — picks which Prayer to Nuffle the
//!   winning team receives (reachable in a mirror match: it compares two D6 rolls, not TVs);
//! * `bb2020/StepPrayers`, `bb2025/start/StepPrayers` — the pre-game underdog prayers;
//! * `bb2025/inducements/StepThrowARock`, `bb2020/end/StepAssignTouchdowns`.
//!
//! Left alone that is non-deterministic *within Java itself*, so no port could mirror it. The
//! parity harness therefore seeds `java.util.Collections`' shared `Random` per game by reflection
//! (`ParityRunner`, with `--add-opens java.base/java.util=ALL-UNNAMED`), which makes Java
//! reproducible — and this module reproduces the identical permutation on the Rust side.
//!
//! Both algorithms are precisely specified, so this is a faithful translation rather than an
//! approximation:
//!
//! * `java.util.Random`: a 48-bit LCG, `seed = (seed ^ 0x5DEECE66D) & ((1 << 48) - 1)`, and
//!   `next(bits)` advancing by `seed * 0x5DEECE66D + 0xB`.
//! * `Collections.shuffle(list, rnd)`: `for (int i = size; i > 1; i--) swap(list, i - 1,
//!   rnd.nextInt(i));`
//!
//! # Stream discipline
//!
//! The seeded `Collections` RNG is a SHARED stream for the whole game, exactly like the dice
//! stream: every `shuffle` call draws from it in sequence. If a second shuffle site becomes
//! reachable in a matchup, Rust must call `collections_shuffle` at the same points and in the same
//! order, or the permutations diverge from that point on.

const MULTIPLIER: u64 = 0x5DEE_CE66D;
const ADDEND: u64 = 0xB;
const MASK: u64 = (1 << 48) - 1;

/// 1:1 translation of `java.util.Random`.
#[derive(Debug, Clone)]
pub struct JavaRandom {
    seed: u64,
}

impl Default for JavaRandom {
    /// Java's `new Random(0)` — only a placeholder; the driver re-seeds per game from the parity
    /// seed, matching `ParityRunner.seedCollectionsShuffleRng`.
    fn default() -> Self { Self::new(0) }
}

impl JavaRandom {
    /// Java: `public Random(long seed) { this.seed = (seed ^ 0x5DEECE66DL) & ((1L << 48) - 1); }`
    pub fn new(seed: i64) -> Self {
        Self { seed: ((seed as u64) ^ MULTIPLIER) & MASK }
    }

    /// Java: `protected int next(int bits)` — returns a SIGNED 32-bit value.
    fn next(&mut self, bits: u32) -> i32 {
        self.seed = (self.seed.wrapping_mul(MULTIPLIER).wrapping_add(ADDEND)) & MASK;
        (self.seed >> (48 - bits)) as u32 as i32
    }

    /// Java: `public int nextInt(int bound)`, including the power-of-two shortcut and the
    /// rejection loop that keeps the distribution uniform.
    ///
    /// ```java
    /// if ((bound & -bound) == bound)  // i.e. bound is a power of 2
    ///     return (int)((bound * (long)next(31)) >> 31);
    /// int bits, val;
    /// do { bits = next(31); val = bits % bound; }
    /// while (bits - val + (bound - 1) < 0);
    /// return val;
    /// ```
    pub fn next_int(&mut self, bound: i32) -> i32 {
        assert!(bound > 0, "bound must be positive");
        if (bound & -bound) == bound {
            let n = self.next(31) as i64;
            return ((bound as i64).wrapping_mul(n) >> 31) as i32;
        }
        loop {
            let bits = self.next(31);
            let val = bits % bound;
            // Java's overflow check, reproduced with wrapping arithmetic.
            if bits.wrapping_sub(val).wrapping_add(bound - 1) >= 0 {
                return val;
            }
        }
    }
}

/// 1:1 translation of `java.util.Collections.shuffle(List, Random)`:
/// `for (int i = size; i > 1; i--) swap(list, i - 1, rnd.nextInt(i));`
pub fn collections_shuffle<T>(list: &mut [T], rnd: &mut JavaRandom) {
    let size = list.len();
    let mut i = size;
    while i > 1 {
        let j = rnd.next_int(i as i32) as usize;
        list.swap(i - 1, j);
        i -= 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Ground truth captured by RUNNING the JVM (Temurin 17.0.18), not generated by this port —
    /// otherwise the test would only confirm the port agrees with itself. Reproduce with:
    ///
    /// ```java
    /// Random r = new Random(seed);
    /// for (int i = 0; i < 6; i++) System.out.print(r.nextInt(8) + ",");  // power-of-two path
    /// for (int i = 0; i < 6; i++) System.out.print(r.nextInt(7) + ",");  // rejection path
    /// ```
    #[test]
    fn next_int_matches_the_jvm() {
        // (seed, six nextInt(8) then six nextInt(7))
        let vectors: &[(i64, [i32; 12])] = &[
            (0,          [5, 6, 1, 4, 5, 2, 2, 1, 6, 2, 1, 2]),
            (1,          [5, 0, 3, 3, 1, 0, 0, 1, 3, 6, 5, 5]),
            (12345,      [2, 4, 7, 7, 6, 0, 2, 4, 6, 1, 1, 1]),
            (987654321,  [2, 7, 6, 1, 0, 1, 0, 2, 2, 4, 6, 0]),
            (-42,        [2, 3, 0, 5, 2, 6, 4, 3, 4, 3, 4, 3]),
        ];
        for (seed, expected) in vectors {
            let mut r = JavaRandom::new(*seed);
            let mut got = [0i32; 12];
            for slot in got.iter_mut().take(6) { *slot = r.next_int(8); }
            for slot in got.iter_mut().skip(6) { *slot = r.next_int(7); }
            assert_eq!(&got, expected, "java.util.Random(seed={seed}) mismatch");
        }
    }

    /// Ground truth captured by running the JVM with `Collections`' shared `Random` seeded by
    /// reflection, then `Collections.shuffle(list)` on `[1..=n]` — the exact call the engine makes.
    #[test]
    fn collections_shuffle_matches_the_jvm() {
        let vectors: &[(i64, &[i32])] = &[
            (0,         &[1, 2]),
            (0,         &[3, 2, 1]),
            (0,         &[1, 8, 4, 5, 7, 2, 3, 6]),
            (0,         &[2, 1, 7, 13, 12, 4, 10, 3, 11, 8, 9, 5, 6]),
            (1,         &[1, 2]),
            (1,         &[2, 3, 1]),
            (1,         &[3, 7, 8, 1, 4, 2, 5, 6]),
            (1,         &[6, 7, 2, 3, 10, 12, 8, 1, 11, 4, 9, 13, 5]),
            (12345,     &[2, 1]),
            (12345,     &[1, 3, 2]),
            (12345,     &[7, 1, 2, 5, 6, 4, 8, 3]),
            (12345,     &[4, 13, 11, 6, 2, 8, 3, 1, 12, 9, 7, 5, 10]),
            (987654321, &[2, 1]),
            (987654321, &[1, 2, 3]),
            (987654321, &[4, 7, 6, 1, 2, 8, 5, 3]),
            (987654321, &[5, 7, 13, 12, 4, 3, 9, 10, 1, 2, 6, 8, 11]),
            (-42,       &[2, 1]),
            (-42,       &[2, 3, 1]),
            (-42,       &[4, 8, 1, 7, 2, 5, 6, 3]),
            (-42,       &[6, 9, 3, 8, 13, 2, 5, 10, 1, 12, 4, 7, 11]),
        ];
        for (seed, expected) in vectors {
            let n = expected.len();
            let mut list: Vec<i32> = (1..=n as i32).collect();
            let mut rnd = JavaRandom::new(*seed);
            collections_shuffle(&mut list, &mut rnd);
            assert_eq!(&list[..], *expected,
                "Collections.shuffle(seed={seed}, n={n}) mismatch");
        }
    }

    /// A single-element list must consume NO randomness — Java's loop body never runs. This
    /// matters for stream discipline: a shuffle of one available prayer must not advance the
    /// shared stream, or every later shuffle in the game diverges.
    #[test]
    fn shuffle_of_one_or_zero_elements_draws_nothing() {
        for n in [0usize, 1] {
            let mut list: Vec<i32> = (1..=n as i32).collect();
            let mut rnd = JavaRandom::new(12345);
            let before = rnd.clone();
            collections_shuffle(&mut list, &mut rnd);
            assert_eq!(rnd.seed, before.seed, "shuffle of {n} elements must not draw");
        }
    }
}
