use serde::{Deserialize, Serialize};

/// 1:1 translation of com.fumbbl.ffb.CommonProperty.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CommonProperty {
    CLIENT_COMMAND_COMPRESSION,
    CLIENT_PING_INTERVAL,
    CLIENT_DEBUG_STATE,
    HTTPCLIENT_TIMEOUT_CONNECT,
    HTTPCLIENT_TIMEOUT_SOCKET,
    SETTING_RE_ROLL_BALL_AND_CHAIN,
    SETTING_PLAYER_MARKING_TYPE,
    SETTING_SOUND_MODE,
    SETTING_SOUND_VOLUME,
    SETTING_ICONS,
    SETTING_AUTOMOVE,
    SETTING_BLITZ_TARGET_PANEL,
    SETTING_GAZE_TARGET_PANEL,
    SETTING_RIGHT_CLICK_END_ACTION,
    SETTING_PITCH_CUSTOMIZATION,
    SETTING_PITCH_MARKINGS,
    SETTING_PITCH_MARKINGS_ROW,
    SETTING_TEAM_LOGOS,
    SETTING_PITCH_WEATHER,
    SETTING_RANGEGRID,
    SETTING_MARK_USED_PLAYERS,
    SETTING_SHOW_AUTO_MARKING_DIALOG,
    SETTING_SWAP_TEAM_COLORS,
    SETTING_BACKGROUND_CHAT,
    SETTING_BACKGROUND_LOG,
    SETTING_BACKGROUND_FRAME,
    SETTING_BACKGROUND_FRAME_COLOR,
    SETTING_BACKGROUND_MENTION,
    SETTING_FONT_COLOR_TEXT,
    SETTING_FONT_COLOR_AWAY,
    SETTING_FONT_COLOR_HOME,
    SETTING_FONT_COLOR_SPEC,
    SETTING_FONT_COLOR_DEV,
    SETTING_FONT_COLOR_ADMIN,
    SETTING_FONT_COLOR_FRAME,
    SETTING_FONT_COLOR_FRAME_SHADOW,
    SETTING_FONT_COLOR_INPUT,
    SETTING_FONT_COLOR_PLAYER_MARKER_HOME,
    SETTING_FONT_COLOR_PLAYER_MARKER_AWAY,
    SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME,
    SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY,
    SETTING_FONT_COLOR_FIELD_MARKER,
    SETTING_FONT_COLOR_MENTION,
    SETTING_TZ_COLOR_HOME,
    SETTING_TZ_COLOR_AWAY,
    SETTING_LAST_CHANGE_LOG_FINGERPRINT,
    SETTING_LOCAL_SETTINGS,
    SETTING_SHOW_CRATERS_AND_BLOODSPOTS,
    SETTING_SWEET_SPOT,
    SETTING_LOCAL_ICON_CACHE,
    SETTING_LOCAL_ICON_CACHE_PATH,
    SETTING_SCALE_FACTOR,
    SETTING_UI_LAYOUT,
    SETTING_UI,
    SETTING_LOG,
    SETTING_LOG_DIR,
    SETTING_LOG_MODE,
    SETTING_SKETCH_CURSOR,
    SETTING_TACKLEZONES_PLAYER_MODE,
    SETTING_TACKLEZONES_SPECTATOR_MODE,
    SETTING_TACKLEZONES_OVERLAP,
    SETTING_TACKLEZONES_CONTOUR,
    SETTING_CLICK_START_SKETCH,
    SETTING_CLICK_ADD_POINT,
    SETTING_CLICK_END_SKETCH,
    SETTING_AUTOCOMPLETE,
}

impl CommonProperty {
    pub fn get_key(self) -> &'static str {
        match self {
            CommonProperty::CLIENT_COMMAND_COMPRESSION => "client.command.compression",
            CommonProperty::CLIENT_PING_INTERVAL => "client.ping.interval",
            CommonProperty::CLIENT_DEBUG_STATE => "client.debug.state",
            CommonProperty::HTTPCLIENT_TIMEOUT_CONNECT => "httpclient.timeout.connect",
            CommonProperty::HTTPCLIENT_TIMEOUT_SOCKET => "httpclient.timeout.socket",
            CommonProperty::SETTING_RE_ROLL_BALL_AND_CHAIN => "setting.reRollBallAndChain",
            CommonProperty::SETTING_PLAYER_MARKING_TYPE => "setting.playerMarkingType",
            CommonProperty::SETTING_SOUND_MODE => "setting.sound.mode",
            CommonProperty::SETTING_SOUND_VOLUME => "setting.sound.volume",
            CommonProperty::SETTING_ICONS => "setting.icons",
            CommonProperty::SETTING_AUTOMOVE => "setting.automove",
            CommonProperty::SETTING_BLITZ_TARGET_PANEL => "setting.blitzTargetPanel",
            CommonProperty::SETTING_GAZE_TARGET_PANEL => "setting.gazeTargetPanel",
            CommonProperty::SETTING_RIGHT_CLICK_END_ACTION => "setting.rightClickEndAction",
            CommonProperty::SETTING_PITCH_CUSTOMIZATION => "setting.pitch.customization",
            CommonProperty::SETTING_PITCH_MARKINGS => "setting.pitch.markings",
            CommonProperty::SETTING_PITCH_MARKINGS_ROW => "setting.pitch.markings.row",
            CommonProperty::SETTING_TEAM_LOGOS => "setting.pitch.teamLogos",
            CommonProperty::SETTING_PITCH_WEATHER => "setting.pitch.weather",
            CommonProperty::SETTING_RANGEGRID => "setting.rangegrid",
            CommonProperty::SETTING_MARK_USED_PLAYERS => "setting.mark.used.players",
            CommonProperty::SETTING_SHOW_AUTO_MARKING_DIALOG => "setting.show.autoMarkingDialog",
            CommonProperty::SETTING_SWAP_TEAM_COLORS => "setting.swap.team.colors",
            CommonProperty::SETTING_BACKGROUND_CHAT => "setting.background.chat",
            CommonProperty::SETTING_BACKGROUND_LOG => "setting.background.log",
            CommonProperty::SETTING_BACKGROUND_FRAME => "setting.background.frame",
            CommonProperty::SETTING_BACKGROUND_FRAME_COLOR => "setting.background.frame.color",
            CommonProperty::SETTING_BACKGROUND_MENTION => "setting.background.mention",
            CommonProperty::SETTING_FONT_COLOR_TEXT => "setting.font.color.text",
            CommonProperty::SETTING_FONT_COLOR_AWAY => "setting.font.color.away",
            CommonProperty::SETTING_FONT_COLOR_HOME => "setting.font.color.home",
            CommonProperty::SETTING_FONT_COLOR_SPEC => "setting.font.color.spec",
            CommonProperty::SETTING_FONT_COLOR_DEV => "setting.font.color.dev",
            CommonProperty::SETTING_FONT_COLOR_ADMIN => "setting.font.color.admin",
            CommonProperty::SETTING_FONT_COLOR_FRAME => "setting.font.color.frame",
            CommonProperty::SETTING_FONT_COLOR_FRAME_SHADOW => "setting.font.color.frameShadow",
            CommonProperty::SETTING_FONT_COLOR_INPUT => "setting.font.color.input",
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_HOME => "setting.font.color.playerMarkerHome",
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_AWAY => "setting.font.color.playerMarkerAway",
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME => "setting.font.color.addPlayerMarkerHome",
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY => "setting.font.color.addPlayerMarkerAway",
            CommonProperty::SETTING_FONT_COLOR_FIELD_MARKER => "setting.font.color.fieldMarker",
            CommonProperty::SETTING_FONT_COLOR_MENTION => "setting.font.color.mention",
            CommonProperty::SETTING_TZ_COLOR_HOME => "setting.tz.color.home",
            CommonProperty::SETTING_TZ_COLOR_AWAY => "setting.tz.color.away",
            CommonProperty::SETTING_LAST_CHANGE_LOG_FINGERPRINT => "setting.lastChangeLogFingerPrint",
            CommonProperty::SETTING_LOCAL_SETTINGS => "setting.localSettings",
            CommonProperty::SETTING_SHOW_CRATERS_AND_BLOODSPOTS => "setting.showCratersAndBloodspots",
            CommonProperty::SETTING_SWEET_SPOT => "setting.sweet.spot",
            CommonProperty::SETTING_LOCAL_ICON_CACHE => "setting.localIconCache",
            CommonProperty::SETTING_LOCAL_ICON_CACHE_PATH => "setting.localIconCache.path",
            CommonProperty::SETTING_SCALE_FACTOR => "setting.scaleFactor",
            CommonProperty::SETTING_UI_LAYOUT => "setting.pitch.orientation",
            CommonProperty::SETTING_UI => "setting.ui",
            CommonProperty::SETTING_LOG => "setting.log",
            CommonProperty::SETTING_LOG_DIR => "setting.log.dir",
            CommonProperty::SETTING_LOG_MODE => "setting.log.mode",
            CommonProperty::SETTING_SKETCH_CURSOR => "setting.sketchCursor",
            CommonProperty::SETTING_TACKLEZONES_PLAYER_MODE => "setting.tacklezones.playerMode",
            CommonProperty::SETTING_TACKLEZONES_SPECTATOR_MODE => "setting.tacklezones.spectatorMode",
            CommonProperty::SETTING_TACKLEZONES_OVERLAP => "setting.tacklezones.overlap",
            CommonProperty::SETTING_TACKLEZONES_CONTOUR => "setting.tacklezones.contour",
            CommonProperty::SETTING_CLICK_START_SKETCH => "setting.click.startSketch",
            CommonProperty::SETTING_CLICK_ADD_POINT => "setting.click.addPoint",
            CommonProperty::SETTING_CLICK_END_SKETCH => "setting.click.endSketch",
            CommonProperty::SETTING_AUTOCOMPLETE => "setting.autocomplete",
        }
    }

    pub fn get_value(self) -> Option<&'static str> {
        match self {
            CommonProperty::CLIENT_COMMAND_COMPRESSION => None,
            CommonProperty::CLIENT_PING_INTERVAL => None,
            CommonProperty::CLIENT_DEBUG_STATE => None,
            CommonProperty::HTTPCLIENT_TIMEOUT_CONNECT => None,
            CommonProperty::HTTPCLIENT_TIMEOUT_SOCKET => None,
            CommonProperty::SETTING_RE_ROLL_BALL_AND_CHAIN => Some("Ask for Whirling Dervish"),
            CommonProperty::SETTING_PLAYER_MARKING_TYPE => Some("Player Marking"),
            CommonProperty::SETTING_SOUND_MODE => Some("Sound"),
            CommonProperty::SETTING_SOUND_VOLUME => Some("Sound Volume"),
            CommonProperty::SETTING_ICONS => Some("Icons"),
            CommonProperty::SETTING_AUTOMOVE => Some("Automove"),
            CommonProperty::SETTING_BLITZ_TARGET_PANEL => Some("Blitz Target Panel"),
            CommonProperty::SETTING_GAZE_TARGET_PANEL => Some("Gaze Target Panel"),
            CommonProperty::SETTING_RIGHT_CLICK_END_ACTION => Some("Right Click Behaviour"),
            CommonProperty::SETTING_PITCH_CUSTOMIZATION => Some("Pitch Customization"),
            CommonProperty::SETTING_PITCH_MARKINGS => Some("Distance Markings"),
            CommonProperty::SETTING_PITCH_MARKINGS_ROW => Some("Row Markings"),
            CommonProperty::SETTING_TEAM_LOGOS => Some("Team Logo"),
            CommonProperty::SETTING_PITCH_WEATHER => Some("Pitch Weather"),
            CommonProperty::SETTING_RANGEGRID => Some("Range Grid"),
            CommonProperty::SETTING_MARK_USED_PLAYERS => Some("Mark used players"),
            CommonProperty::SETTING_SHOW_AUTO_MARKING_DIALOG => Some("Show automarking dialog"),
            CommonProperty::SETTING_SWAP_TEAM_COLORS => Some("Swap team colors"),
            CommonProperty::SETTING_BACKGROUND_CHAT => Some("Chat"),
            CommonProperty::SETTING_BACKGROUND_LOG => Some("Log"),
            CommonProperty::SETTING_BACKGROUND_FRAME => Some("Frame"),
            CommonProperty::SETTING_BACKGROUND_FRAME_COLOR => Some("Color"),
            CommonProperty::SETTING_BACKGROUND_MENTION => Some("Mention"),
            CommonProperty::SETTING_FONT_COLOR_TEXT => Some("Regular text"),
            CommonProperty::SETTING_FONT_COLOR_AWAY => Some("Away text"),
            CommonProperty::SETTING_FONT_COLOR_HOME => Some("Home text"),
            CommonProperty::SETTING_FONT_COLOR_SPEC => Some("Spectators text"),
            CommonProperty::SETTING_FONT_COLOR_DEV => Some("Devs text"),
            CommonProperty::SETTING_FONT_COLOR_ADMIN => Some("Admin text"),
            CommonProperty::SETTING_FONT_COLOR_FRAME => Some("Sidebar/Scoreboard"),
            CommonProperty::SETTING_FONT_COLOR_FRAME_SHADOW => Some("Sidebar/Scoreboard shadow"),
            CommonProperty::SETTING_FONT_COLOR_INPUT => Some("Chat input"),
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_HOME => Some("Home Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_AWAY => Some("Away Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME => Some("Additional Home Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY => Some("Additional Away Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_FIELD_MARKER => Some("Field Marker"),
            CommonProperty::SETTING_FONT_COLOR_MENTION => Some("Mention"),
            CommonProperty::SETTING_TZ_COLOR_HOME => Some("Tacklezones Home"),
            CommonProperty::SETTING_TZ_COLOR_AWAY => Some("Tacklezones Away"),
            CommonProperty::SETTING_LAST_CHANGE_LOG_FINGERPRINT => Some("What's new?"),
            CommonProperty::SETTING_LOCAL_SETTINGS => Some("Local Stored Settings"),
            CommonProperty::SETTING_SHOW_CRATERS_AND_BLOODSPOTS => Some("Craters and bloodspots"),
            CommonProperty::SETTING_SWEET_SPOT => Some("Show Sweet Spot"),
            CommonProperty::SETTING_LOCAL_ICON_CACHE => Some("Local Icon Cache"),
            CommonProperty::SETTING_LOCAL_ICON_CACHE_PATH => Some("Local Icon Cache Folder"),
            CommonProperty::SETTING_SCALE_FACTOR => Some("Client Size"),
            CommonProperty::SETTING_UI_LAYOUT => Some("Client Layout"),
            CommonProperty::SETTING_UI => Some("Client UI"),
            CommonProperty::SETTING_LOG => Some("Client Logging"),
            CommonProperty::SETTING_LOG_DIR => Some("Logging Folder"),
            CommonProperty::SETTING_LOG_MODE => Some("Logging on/off"),
            CommonProperty::SETTING_SKETCH_CURSOR => Some("Sketch Cursor"),
            CommonProperty::SETTING_TACKLEZONES_PLAYER_MODE => Some("Player Mode"),
            CommonProperty::SETTING_TACKLEZONES_SPECTATOR_MODE => Some("Spectator Mode"),
            CommonProperty::SETTING_TACKLEZONES_OVERLAP => Some("Overlap"),
            CommonProperty::SETTING_TACKLEZONES_CONTOUR => Some("Contour"),
            CommonProperty::SETTING_CLICK_START_SKETCH => Some("Start Sketch Click"),
            CommonProperty::SETTING_CLICK_ADD_POINT => Some("Add Point Click"),
            CommonProperty::SETTING_CLICK_END_SKETCH => Some("End Sketch Click"),
            CommonProperty::SETTING_AUTOCOMPLETE => Some("Autocomplete"),
        }
    }

    pub fn get_category(self) -> &'static str {
        match self {
            CommonProperty::CLIENT_COMMAND_COMPRESSION => "",
            CommonProperty::CLIENT_PING_INTERVAL => "",
            CommonProperty::CLIENT_DEBUG_STATE => "",
            CommonProperty::HTTPCLIENT_TIMEOUT_CONNECT => "",
            CommonProperty::HTTPCLIENT_TIMEOUT_SOCKET => "",
            CommonProperty::SETTING_RE_ROLL_BALL_AND_CHAIN => "Gameplay",
            CommonProperty::SETTING_PLAYER_MARKING_TYPE => "Configuration",
            CommonProperty::SETTING_SOUND_MODE => "Configuration",
            CommonProperty::SETTING_SOUND_VOLUME => "Configuration",
            CommonProperty::SETTING_ICONS => "Graphics",
            CommonProperty::SETTING_AUTOMOVE => "Gameplay",
            CommonProperty::SETTING_BLITZ_TARGET_PANEL => "Gameplay",
            CommonProperty::SETTING_GAZE_TARGET_PANEL => "Gameplay",
            CommonProperty::SETTING_RIGHT_CLICK_END_ACTION => "Gameplay",
            CommonProperty::SETTING_PITCH_CUSTOMIZATION => "Graphics",
            CommonProperty::SETTING_PITCH_MARKINGS => "Graphics",
            CommonProperty::SETTING_PITCH_MARKINGS_ROW => "Graphics",
            CommonProperty::SETTING_TEAM_LOGOS => "Graphics",
            CommonProperty::SETTING_PITCH_WEATHER => "Graphics",
            CommonProperty::SETTING_RANGEGRID => "Gameplay",
            CommonProperty::SETTING_MARK_USED_PLAYERS => "Gameplay",
            CommonProperty::SETTING_SHOW_AUTO_MARKING_DIALOG => "Configuration",
            CommonProperty::SETTING_SWAP_TEAM_COLORS => "Graphics",
            CommonProperty::SETTING_BACKGROUND_CHAT => "Background",
            CommonProperty::SETTING_BACKGROUND_LOG => "Background",
            CommonProperty::SETTING_BACKGROUND_FRAME => "Background",
            CommonProperty::SETTING_BACKGROUND_FRAME_COLOR => "Background",
            CommonProperty::SETTING_BACKGROUND_MENTION => "Background",
            CommonProperty::SETTING_FONT_COLOR_TEXT => "Color",
            CommonProperty::SETTING_FONT_COLOR_AWAY => "Color",
            CommonProperty::SETTING_FONT_COLOR_HOME => "Color",
            CommonProperty::SETTING_FONT_COLOR_SPEC => "Color",
            CommonProperty::SETTING_FONT_COLOR_DEV => "Color",
            CommonProperty::SETTING_FONT_COLOR_ADMIN => "Color",
            CommonProperty::SETTING_FONT_COLOR_FRAME => "Color",
            CommonProperty::SETTING_FONT_COLOR_FRAME_SHADOW => "Color",
            CommonProperty::SETTING_FONT_COLOR_INPUT => "Color",
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_HOME => "Color",
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_AWAY => "Color",
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME => "Color",
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY => "Color",
            CommonProperty::SETTING_FONT_COLOR_FIELD_MARKER => "Color",
            CommonProperty::SETTING_FONT_COLOR_MENTION => "Color",
            CommonProperty::SETTING_TZ_COLOR_HOME => "Color",
            CommonProperty::SETTING_TZ_COLOR_AWAY => "Color",
            CommonProperty::SETTING_LAST_CHANGE_LOG_FINGERPRINT => "Configuration",
            CommonProperty::SETTING_LOCAL_SETTINGS => "",
            CommonProperty::SETTING_SHOW_CRATERS_AND_BLOODSPOTS => "Graphics",
            CommonProperty::SETTING_SWEET_SPOT => "Configuration",
            CommonProperty::SETTING_LOCAL_ICON_CACHE => "Configuration",
            CommonProperty::SETTING_LOCAL_ICON_CACHE_PATH => "Configuration",
            CommonProperty::SETTING_SCALE_FACTOR => "Configuration",
            CommonProperty::SETTING_UI_LAYOUT => "Configuration",
            CommonProperty::SETTING_UI => "Configuration",
            CommonProperty::SETTING_LOG => "Configuration",
            CommonProperty::SETTING_LOG_DIR => "Configuration",
            CommonProperty::SETTING_LOG_MODE => "Configuration",
            CommonProperty::SETTING_SKETCH_CURSOR => "Configuration",
            CommonProperty::SETTING_TACKLEZONES_PLAYER_MODE => "Gameplay",
            CommonProperty::SETTING_TACKLEZONES_SPECTATOR_MODE => "Gameplay",
            CommonProperty::SETTING_TACKLEZONES_OVERLAP => "Gameplay",
            CommonProperty::SETTING_TACKLEZONES_CONTOUR => "Gameplay",
            CommonProperty::SETTING_CLICK_START_SKETCH => "Configuration",
            CommonProperty::SETTING_CLICK_ADD_POINT => "Configuration",
            CommonProperty::SETTING_CLICK_END_SKETCH => "Configuration",
            CommonProperty::SETTING_AUTOCOMPLETE => "Configuration",
        }
    }

    pub fn get_dialog_value(self) -> Option<&'static str> {
        match self {
            CommonProperty::CLIENT_COMMAND_COMPRESSION => None,
            CommonProperty::CLIENT_PING_INTERVAL => None,
            CommonProperty::CLIENT_DEBUG_STATE => None,
            CommonProperty::HTTPCLIENT_TIMEOUT_CONNECT => None,
            CommonProperty::HTTPCLIENT_TIMEOUT_SOCKET => None,
            CommonProperty::SETTING_RE_ROLL_BALL_AND_CHAIN => Some("Ask for Whirling Dervish"),
            CommonProperty::SETTING_PLAYER_MARKING_TYPE => Some("Player Marking"),
            CommonProperty::SETTING_SOUND_MODE => Some("Sound On/Mute Specs/Off"),
            CommonProperty::SETTING_SOUND_VOLUME => Some("Sound Volume"),
            CommonProperty::SETTING_ICONS => Some("Icons"),
            CommonProperty::SETTING_AUTOMOVE => Some("Automove"),
            CommonProperty::SETTING_BLITZ_TARGET_PANEL => Some("Blitz Target Panel"),
            CommonProperty::SETTING_GAZE_TARGET_PANEL => Some("Gaze Target Panel"),
            CommonProperty::SETTING_RIGHT_CLICK_END_ACTION => Some("Right Click Behaviour"),
            CommonProperty::SETTING_PITCH_CUSTOMIZATION => Some("Pitch Customization"),
            CommonProperty::SETTING_PITCH_MARKINGS => Some("Distance Markings"),
            CommonProperty::SETTING_PITCH_MARKINGS_ROW => Some("Row Markings"),
            CommonProperty::SETTING_TEAM_LOGOS => Some("Team Logo"),
            CommonProperty::SETTING_PITCH_WEATHER => Some("Pitch Weather"),
            CommonProperty::SETTING_RANGEGRID => Some("Range Grid"),
            CommonProperty::SETTING_MARK_USED_PLAYERS => Some("Mark used players"),
            CommonProperty::SETTING_SHOW_AUTO_MARKING_DIALOG => Some("Show automarking dialog"),
            CommonProperty::SETTING_SWAP_TEAM_COLORS => Some("Swap team colors"),
            CommonProperty::SETTING_BACKGROUND_CHAT => Some("Chat Color"),
            CommonProperty::SETTING_BACKGROUND_LOG => Some("Log Color"),
            CommonProperty::SETTING_BACKGROUND_FRAME => Some("Frame Graphics/Color"),
            CommonProperty::SETTING_BACKGROUND_FRAME_COLOR => Some("Frame Color"),
            CommonProperty::SETTING_BACKGROUND_MENTION => Some("FMention Color"),
            CommonProperty::SETTING_FONT_COLOR_TEXT => Some("Regular text"),
            CommonProperty::SETTING_FONT_COLOR_AWAY => Some("Away text"),
            CommonProperty::SETTING_FONT_COLOR_HOME => Some("Home text"),
            CommonProperty::SETTING_FONT_COLOR_SPEC => Some("Spectators text"),
            CommonProperty::SETTING_FONT_COLOR_DEV => Some("Devs text"),
            CommonProperty::SETTING_FONT_COLOR_ADMIN => Some("Admin text"),
            CommonProperty::SETTING_FONT_COLOR_FRAME => Some("Sidebar/Scoreboard"),
            CommonProperty::SETTING_FONT_COLOR_FRAME_SHADOW => Some("Sidebar/Scoreboard shadow"),
            CommonProperty::SETTING_FONT_COLOR_INPUT => Some("Chat input"),
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_HOME => Some("Home Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_AWAY => Some("Away Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME => Some("Additional Home Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY => Some("Additional Away Player Marker"),
            CommonProperty::SETTING_FONT_COLOR_FIELD_MARKER => Some("Field Marker"),
            CommonProperty::SETTING_FONT_COLOR_MENTION => Some("Mention"),
            CommonProperty::SETTING_TZ_COLOR_HOME => Some("Tacklezones Home"),
            CommonProperty::SETTING_TZ_COLOR_AWAY => Some("Tacklezones Away"),
            CommonProperty::SETTING_LAST_CHANGE_LOG_FINGERPRINT => Some("What's new?"),
            CommonProperty::SETTING_LOCAL_SETTINGS => Some("Local Stored Settings"),
            CommonProperty::SETTING_SHOW_CRATERS_AND_BLOODSPOTS => Some("Craters and bloodspots"),
            CommonProperty::SETTING_SWEET_SPOT => Some("Show Sweet Spot"),
            CommonProperty::SETTING_LOCAL_ICON_CACHE => Some("Local Icon Cache"),
            CommonProperty::SETTING_LOCAL_ICON_CACHE_PATH => Some("Local Icon Cache Folder"),
            CommonProperty::SETTING_SCALE_FACTOR => Some("Client Size"),
            CommonProperty::SETTING_UI_LAYOUT => Some("Client Layout"),
            CommonProperty::SETTING_UI => Some("Client UI"),
            CommonProperty::SETTING_LOG => Some("Client Logging"),
            CommonProperty::SETTING_LOG_DIR => Some("Logging Folder"),
            CommonProperty::SETTING_LOG_MODE => Some("Logging on/off"),
            CommonProperty::SETTING_SKETCH_CURSOR => Some("Sketch Cursor"),
            CommonProperty::SETTING_TACKLEZONES_PLAYER_MODE => Some("Tacklezones: Player Mode"),
            CommonProperty::SETTING_TACKLEZONES_SPECTATOR_MODE => Some("Tacklezones: Spectator Mode"),
            CommonProperty::SETTING_TACKLEZONES_OVERLAP => Some("Overlap"),
            CommonProperty::SETTING_TACKLEZONES_CONTOUR => Some("Contour"),
            CommonProperty::SETTING_CLICK_START_SKETCH => Some("Start Sketch Click"),
            CommonProperty::SETTING_CLICK_ADD_POINT => Some("Add Point Click"),
            CommonProperty::SETTING_CLICK_END_SKETCH => Some("End Sketch Click"),
            CommonProperty::SETTING_AUTOCOMPLETE => Some("Autocomplete"),
        }
    }

    pub fn is_stored_remote(self) -> bool {
        match self {
            CommonProperty::SETTING_LOCAL_SETTINGS => true,
            _ => false,
        }
    }

    pub fn for_key(key: &str) -> Option<Self> {
        Self::all().iter().copied().find(|v| v.get_key().eq_ignore_ascii_case(key))
    }

    pub fn all() -> &'static [CommonProperty] {
        &[
            CommonProperty::CLIENT_COMMAND_COMPRESSION,
            CommonProperty::CLIENT_PING_INTERVAL,
            CommonProperty::CLIENT_DEBUG_STATE,
            CommonProperty::HTTPCLIENT_TIMEOUT_CONNECT,
            CommonProperty::HTTPCLIENT_TIMEOUT_SOCKET,
            CommonProperty::SETTING_RE_ROLL_BALL_AND_CHAIN,
            CommonProperty::SETTING_PLAYER_MARKING_TYPE,
            CommonProperty::SETTING_SOUND_MODE,
            CommonProperty::SETTING_SOUND_VOLUME,
            CommonProperty::SETTING_ICONS,
            CommonProperty::SETTING_AUTOMOVE,
            CommonProperty::SETTING_BLITZ_TARGET_PANEL,
            CommonProperty::SETTING_GAZE_TARGET_PANEL,
            CommonProperty::SETTING_RIGHT_CLICK_END_ACTION,
            CommonProperty::SETTING_PITCH_CUSTOMIZATION,
            CommonProperty::SETTING_PITCH_MARKINGS,
            CommonProperty::SETTING_PITCH_MARKINGS_ROW,
            CommonProperty::SETTING_TEAM_LOGOS,
            CommonProperty::SETTING_PITCH_WEATHER,
            CommonProperty::SETTING_RANGEGRID,
            CommonProperty::SETTING_MARK_USED_PLAYERS,
            CommonProperty::SETTING_SHOW_AUTO_MARKING_DIALOG,
            CommonProperty::SETTING_SWAP_TEAM_COLORS,
            CommonProperty::SETTING_BACKGROUND_CHAT,
            CommonProperty::SETTING_BACKGROUND_LOG,
            CommonProperty::SETTING_BACKGROUND_FRAME,
            CommonProperty::SETTING_BACKGROUND_FRAME_COLOR,
            CommonProperty::SETTING_BACKGROUND_MENTION,
            CommonProperty::SETTING_FONT_COLOR_TEXT,
            CommonProperty::SETTING_FONT_COLOR_AWAY,
            CommonProperty::SETTING_FONT_COLOR_HOME,
            CommonProperty::SETTING_FONT_COLOR_SPEC,
            CommonProperty::SETTING_FONT_COLOR_DEV,
            CommonProperty::SETTING_FONT_COLOR_ADMIN,
            CommonProperty::SETTING_FONT_COLOR_FRAME,
            CommonProperty::SETTING_FONT_COLOR_FRAME_SHADOW,
            CommonProperty::SETTING_FONT_COLOR_INPUT,
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_HOME,
            CommonProperty::SETTING_FONT_COLOR_PLAYER_MARKER_AWAY,
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_HOME,
            CommonProperty::SETTING_FONT_COLOR_ADDITIONAL_PLAYER_MARKER_AWAY,
            CommonProperty::SETTING_FONT_COLOR_FIELD_MARKER,
            CommonProperty::SETTING_FONT_COLOR_MENTION,
            CommonProperty::SETTING_TZ_COLOR_HOME,
            CommonProperty::SETTING_TZ_COLOR_AWAY,
            CommonProperty::SETTING_LAST_CHANGE_LOG_FINGERPRINT,
            CommonProperty::SETTING_LOCAL_SETTINGS,
            CommonProperty::SETTING_SHOW_CRATERS_AND_BLOODSPOTS,
            CommonProperty::SETTING_SWEET_SPOT,
            CommonProperty::SETTING_LOCAL_ICON_CACHE,
            CommonProperty::SETTING_LOCAL_ICON_CACHE_PATH,
            CommonProperty::SETTING_SCALE_FACTOR,
            CommonProperty::SETTING_UI_LAYOUT,
            CommonProperty::SETTING_UI,
            CommonProperty::SETTING_LOG,
            CommonProperty::SETTING_LOG_DIR,
            CommonProperty::SETTING_LOG_MODE,
            CommonProperty::SETTING_SKETCH_CURSOR,
            CommonProperty::SETTING_TACKLEZONES_PLAYER_MODE,
            CommonProperty::SETTING_TACKLEZONES_SPECTATOR_MODE,
            CommonProperty::SETTING_TACKLEZONES_OVERLAP,
            CommonProperty::SETTING_TACKLEZONES_CONTOUR,
            CommonProperty::SETTING_CLICK_START_SKETCH,
            CommonProperty::SETTING_CLICK_ADD_POINT,
            CommonProperty::SETTING_CLICK_END_SKETCH,
            CommonProperty::SETTING_AUTOCOMPLETE,
        ]
    }
}
