/// 1:1 translation of `ReportId.java` — all game event identifiers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum ReportId {
    NONE,
    // Internal reports
    NERVES_OF_STEEL,
    // On-wire reports
    ALWAYS_HUNGRY_ROLL,
    ARGUE_THE_CALL,
    CATCH_ROLL,
    CLOUD_BURSTER,
    CONFUSION_ROLL,
    DAUNTLESS_ROLL,
    DODGE_ROLL,
    ESCAPE_ROLL,
    FOUL_APPEARANCE_ROLL,
    GO_FOR_IT_ROLL,
    INTERCEPTION_ROLL,
    JUMP_ROLL,
    PASS_ROLL,
    PICK_UP_ROLL,
    RIGHT_STUFF_ROLL,
    REGENERATION_ROLL,
    SAFE_THROW_ROLL,
    TENTACLES_SHADOWING_ROLL,
    SKILL_USE,
    RE_ROLL,
    TURN_END,
    PLAYER_ACTION,
    FOUL,
    HAND_OVER,
    INJURY,
    APOTHECARY_ROLL,
    APOTHECARY_CHOICE,
    THROW_IN,
    SCATTER_BALL,
    BLOCK,
    BLOCK_CHOICE,
    SPECTATORS,
    WEATHER,
    COIN_THROW,
    RECEIVE_CHOICE,
    KICKOFF_RESULT,
    KICKOFF_SCATTER,
    KICKOFF_EXTRA_RE_ROLL,
    KICKOFF_RIOT,
    KICKOFF_TIMEOUT,
    SOLID_DEFENCE_ROLL,
    QUICK_SNAP_ROLL,
    KICKOFF_SEQUENCE_ACTIVATIONS_COUNT,
    KICKOFF_SEQUENCE_ACTIVATIONS_EXHAUSTED,
    BLITZ_ROLL,
    KICKOFF_OFFICIOUS_REF,
    OFFICIOUS_REF_ROLL,
    KICKOFF_THROW_A_ROCK,
    PUSHBACK,
    REFEREE,
    KICKOFF_PITCH_INVASION,
    DODGY_SNACK_ROLL,
    KICKOFF_DODGY_SNACK,
    THROW_TEAM_MATE_ROLL,
    DEDICATED_FANS,
    SCATTER_PLAYER,
    SWOOP_PLAYER,
    TIMEOUT_ENFORCED,
    WINNINGS,
    WINNINGS_ROLL,
    FUMBBL_RESULT_UPLOAD,
    FAN_FACTOR_ROLL_POST_MATCH,
    MOST_VALUABLE_PLAYERS,
    DEFECTING_PLAYERS,
    JUMP_UP_ROLL,
    STAND_UP_ROLL,
    BRIBES_ROLL,
    MASTER_CHEF_ROLL,
    START_HALF,
    INDUCEMENT,
    PILING_ON,
    CHAINSAW_ROLL,
    LEADER,
    SECRET_WEAPON_BAN,
    BLOOD_LUST_ROLL,
    HYPNOTIC_GAZE_ROLL,
    BITE_SPECTATOR,
    ANIMOSITY_ROLL,
    RAISE_DEAD,
    BLOCK_ROLL,
    PENALTY_SHOOTOUT,
    DOUBLE_HIRED_STAR_PLAYER,
    DOUBLE_HIRED_STAFF,
    SPELL_EFFECT_ROLL,
    WIZARD_USE,
    GAME_OPTIONS,
    PASS_BLOCK,
    NO_PLAYERS_TO_FIELD,
    PLAY_CARD,
    CARD_DEACTIVATED,
    BOMB_OUT_OF_BOUNDS,
    PETTY_CASH,
    FREE_PETTY_CASH,
    INDUCEMENTS_BOUGHT,
    CARDS_BOUGHT,
    CARD_EFFECT_ROLL,
    WEEPING_DAGGER_ROLL,
    KICK_TEAM_MATE_ROLL,
    RIOTOUS_ROOKIES,
    SWARMING_PLAYERS_ROLL,
    PASS_DEVIATE,
    CARDS_AND_INDUCEMENTS_BOUGHT,
    FAN_FACTOR,
    SELECT_BLITZ_TARGET,
    SELECT_GAZE_TARGET,
    BOMB_EXPLODES_AFTER_CATCH,
    PLACE_BALL_DIRECTION,
    FUMBLEROOSKIE,
    ANIMAL_SAVAGERY,
    PROJECTILE_VOMIT,
    BRILLIANT_COACHING_RE_ROLLS_LOST,
    PUMP_UP_THE_CROWD_RE_ROLLS_LOST,
    SHOW_STAR_RE_ROLLS_LOST,
    KICK_TEAM_MATE_FUMBLE,
    BLOCK_RE_ROLL,
    TRAP_DOOR,
    PRAYER_AMOUNT,
    PRAYER_ROLL,
    PRAYER_END,
    PRAYER_WASTED,
    KICKOFF_CHEERING_FANS,
    BRIBERY_AND_CORRUPTION_RE_ROLL,
    PLAYER_EVENT,
    STALLER_DETECTED,
    THROW_AT_STALLING_PLAYER,
    INDOMITABLE,
    OLD_PRO,
    PICK_ME_UP,
    SKILL_WASTED,
    TWO_FOR_ONE,
    MODIFIED_PASS_RESULT,
    MODIFIED_DODGE_RESULT_SUCCESSFUL,
    RAIDING_PARTY,
    EVENT,
    HIT_AND_RUN,
    SKILL_USE_OTHER_PLAYER,
    THROWN_KEG,
    PUMP_UP_THE_CROWD_RE_ROLL,
    SHOW_STAR_RE_ROLL,
    BIASED_REF,
    WEATHER_MAGE_ROLL,
    WEATHER_MAGE_RESULT,
    LOOK_INTO_MY_EYES_ROLL,
    BALEFUL_HEX,
    ALL_YOU_CAN_EAT,
    CATCH_OF_THE_DAY,
    BREATHE_FIRE,
    THEN_I_STARTED_BLASTIN,
    PRAYERS_AND_INDUCEMENTS_BOUGHT,
    THROW_AT_PLAYER,
    STEADY_FOOTING_ROLL,
    MASCOT_USED,
    TEAM_EVENT,
    TEAM_CAPTAIN_ROLL,
    GETTING_EVEN_ROLL,
    SABOTEUR_ROLL,
    CHOMP_ROLL,
    CHOMP_REMOVED,
    PUNT_DIRECTION_ROLL,
    PUNT_DISTANCE_ROLL,
    SWOOP_DIRECTION_ROLL,
    SWOOP_DISTANCE_ROLL,
}

impl ReportId {
    pub fn get_name(&self) -> &'static str {
        match self {
            ReportId::NONE => "none",
            ReportId::NERVES_OF_STEEL => "nervesOfSteel",
            ReportId::ALWAYS_HUNGRY_ROLL => "alwaysHungryRoll",
            ReportId::ARGUE_THE_CALL => "argueTheCall",
            ReportId::CATCH_ROLL => "catchRoll",
            ReportId::CLOUD_BURSTER => "cloudBurster",
            ReportId::CONFUSION_ROLL => "confusionRoll",
            ReportId::DAUNTLESS_ROLL => "dauntlessRoll",
            ReportId::DODGE_ROLL => "dodgeRoll",
            ReportId::ESCAPE_ROLL => "escapeRoll",
            ReportId::FOUL_APPEARANCE_ROLL => "foulAppearanceRoll",
            ReportId::GO_FOR_IT_ROLL => "goForItRoll",
            ReportId::INTERCEPTION_ROLL => "interceptionRoll",
            ReportId::JUMP_ROLL => "leapRoll",
            ReportId::PASS_ROLL => "passRoll",
            ReportId::PICK_UP_ROLL => "pickUpRoll",
            ReportId::RIGHT_STUFF_ROLL => "rightStuffRoll",
            ReportId::REGENERATION_ROLL => "regenerationRoll",
            ReportId::SAFE_THROW_ROLL => "safeThrowRoll",
            ReportId::TENTACLES_SHADOWING_ROLL => "tentaclesShadowingRoll",
            ReportId::SKILL_USE => "skillUse",
            ReportId::RE_ROLL => "reRoll",
            ReportId::TURN_END => "turnEnd",
            ReportId::PLAYER_ACTION => "playerAction",
            ReportId::FOUL => "foul",
            ReportId::HAND_OVER => "handOver",
            ReportId::INJURY => "injury",
            ReportId::APOTHECARY_ROLL => "apothecaryRoll",
            ReportId::APOTHECARY_CHOICE => "apothecaryChoice",
            ReportId::THROW_IN => "throwIn",
            ReportId::SCATTER_BALL => "scatterBall",
            ReportId::BLOCK => "block",
            ReportId::BLOCK_CHOICE => "blockChoice",
            ReportId::SPECTATORS => "spectators",
            ReportId::WEATHER => "weather",
            ReportId::COIN_THROW => "coinThrow",
            ReportId::RECEIVE_CHOICE => "receiveChoice",
            ReportId::KICKOFF_RESULT => "kickoffResult",
            ReportId::KICKOFF_SCATTER => "kickoffScatter",
            ReportId::KICKOFF_EXTRA_RE_ROLL => "extraReRoll",
            ReportId::KICKOFF_RIOT => "kickoffRiot",
            ReportId::KICKOFF_TIMEOUT => "kickoffTimeout",
            ReportId::SOLID_DEFENCE_ROLL => "solidDefenceRoll",
            ReportId::QUICK_SNAP_ROLL => "quickSnapRoll",
            ReportId::KICKOFF_SEQUENCE_ACTIVATIONS_COUNT => "kickoffSequenceActivationsCount",
            ReportId::KICKOFF_SEQUENCE_ACTIVATIONS_EXHAUSTED => "kickoffSequenceActivationsExhausted",
            ReportId::BLITZ_ROLL => "blitzRoll",
            ReportId::KICKOFF_OFFICIOUS_REF => "kickoffOfficiousRef",
            ReportId::OFFICIOUS_REF_ROLL => "officiousRefRoll",
            ReportId::KICKOFF_THROW_A_ROCK => "kickoffThrowARock",
            ReportId::PUSHBACK => "pushback",
            ReportId::REFEREE => "referee",
            ReportId::KICKOFF_PITCH_INVASION => "kickoffPitchInvasion",
            ReportId::DODGY_SNACK_ROLL => "dodgySnackRoll",
            ReportId::KICKOFF_DODGY_SNACK => "kickoffDodgySnack",
            ReportId::THROW_TEAM_MATE_ROLL => "throwTeamMateRoll",
            ReportId::DEDICATED_FANS => "dedicatedFans",
            ReportId::SCATTER_PLAYER => "scatterPlayer",
            ReportId::SWOOP_PLAYER => "swoopPlayer",
            ReportId::TIMEOUT_ENFORCED => "timeoutEnforced",
            ReportId::WINNINGS => "winnings",
            ReportId::WINNINGS_ROLL => "winningsRoll",
            ReportId::FUMBBL_RESULT_UPLOAD => "fumbblResultUpload",
            ReportId::FAN_FACTOR_ROLL_POST_MATCH => "fanFactorRoll",
            ReportId::MOST_VALUABLE_PLAYERS => "mostValuablePlayers",
            ReportId::DEFECTING_PLAYERS => "defectingPlayers",
            ReportId::JUMP_UP_ROLL => "jumpUpRoll",
            ReportId::STAND_UP_ROLL => "standUpRoll",
            ReportId::BRIBES_ROLL => "bribesRoll",
            ReportId::MASTER_CHEF_ROLL => "masterChefRoll",
            ReportId::START_HALF => "startHalf",
            ReportId::INDUCEMENT => "inducement",
            ReportId::PILING_ON => "pilingOn",
            ReportId::CHAINSAW_ROLL => "chainsawRoll",
            ReportId::LEADER => "leader",
            ReportId::SECRET_WEAPON_BAN => "secretWeaponBan",
            ReportId::BLOOD_LUST_ROLL => "bloodLustRoll",
            ReportId::HYPNOTIC_GAZE_ROLL => "hypnoticGazeRoll",
            ReportId::BITE_SPECTATOR => "biteSpectator",
            ReportId::ANIMOSITY_ROLL => "animosityRoll",
            ReportId::RAISE_DEAD => "raiseDead",
            ReportId::BLOCK_ROLL => "blockRoll",
            ReportId::PENALTY_SHOOTOUT => "penaltyShootout",
            ReportId::DOUBLE_HIRED_STAR_PLAYER => "doubleHiredStarPlayer",
            ReportId::DOUBLE_HIRED_STAFF => "doubleHiredStaff",
            ReportId::SPELL_EFFECT_ROLL => "spellEffectRoll",
            ReportId::WIZARD_USE => "wizardUse",
            ReportId::GAME_OPTIONS => "gameOptions",
            ReportId::PASS_BLOCK => "passBlock",
            ReportId::NO_PLAYERS_TO_FIELD => "noPlayersToField",
            ReportId::PLAY_CARD => "playCard",
            ReportId::CARD_DEACTIVATED => "cardDeactivated",
            ReportId::BOMB_OUT_OF_BOUNDS => "bombOutOfBounds",
            ReportId::PETTY_CASH => "pettyCash",
            ReportId::FREE_PETTY_CASH => "freePettyCash",
            ReportId::INDUCEMENTS_BOUGHT => "inducementsBought",
            ReportId::CARDS_BOUGHT => "cardsBought",
            ReportId::CARD_EFFECT_ROLL => "cardEffectRoll",
            ReportId::WEEPING_DAGGER_ROLL => "weepingDaggerRoll",
            ReportId::KICK_TEAM_MATE_ROLL => "kickTeamMateRoll",
            ReportId::RIOTOUS_ROOKIES => "riotousRookies",
            ReportId::SWARMING_PLAYERS_ROLL => "swarmingPlayersRoll",
            ReportId::PASS_DEVIATE => "passDeviate",
            ReportId::CARDS_AND_INDUCEMENTS_BOUGHT => "cardsAndInducementsBought",
            ReportId::FAN_FACTOR => "fanFactor",
            ReportId::SELECT_BLITZ_TARGET => "selectBlitzTarget",
            ReportId::SELECT_GAZE_TARGET => "selectGazeTarget",
            ReportId::BOMB_EXPLODES_AFTER_CATCH => "bombExplodesAfterCatch",
            ReportId::PLACE_BALL_DIRECTION => "placedBallDirection",
            ReportId::FUMBLEROOSKIE => "fumblerooskie",
            ReportId::ANIMAL_SAVAGERY => "animalSavagery",
            ReportId::PROJECTILE_VOMIT => "projectileVomit",
            ReportId::BRILLIANT_COACHING_RE_ROLLS_LOST => "brilliantCoachingReRoll",
            ReportId::PUMP_UP_THE_CROWD_RE_ROLLS_LOST => "pumpUpTheCrowdReRollLost",
            ReportId::SHOW_STAR_RE_ROLLS_LOST => "showStarReRollLost",
            ReportId::KICK_TEAM_MATE_FUMBLE => "kickTeamMateFumble",
            ReportId::BLOCK_RE_ROLL => "blockReRoll",
            ReportId::TRAP_DOOR => "trapDoor",
            ReportId::PRAYER_AMOUNT => "prayerAmount",
            ReportId::PRAYER_ROLL => "prayerRoll",
            ReportId::PRAYER_END => "prayerEnd",
            ReportId::PRAYER_WASTED => "prayerWasted",
            ReportId::KICKOFF_CHEERING_FANS => "cheeringFans",
            ReportId::BRIBERY_AND_CORRUPTION_RE_ROLL => "briberyAndCorruptionReRoll",
            ReportId::PLAYER_EVENT => "playerEvent",
            ReportId::STALLER_DETECTED => "stallerDetected",
            ReportId::THROW_AT_STALLING_PLAYER => "throwAtStallingPlayer",
            ReportId::INDOMITABLE => "indomitable",
            ReportId::OLD_PRO => "oldPro",
            ReportId::PICK_ME_UP => "pickMeUp",
            ReportId::SKILL_WASTED => "skillWasted",
            ReportId::TWO_FOR_ONE => "twoForOne",
            ReportId::MODIFIED_PASS_RESULT => "modifiedPassResult",
            ReportId::MODIFIED_DODGE_RESULT_SUCCESSFUL => "modifiedDodgeResultSuccessful",
            ReportId::RAIDING_PARTY => "raidingParty",
            ReportId::EVENT => "event",
            ReportId::HIT_AND_RUN => "hitAndRun",
            ReportId::SKILL_USE_OTHER_PLAYER => "skillUseOtherPlayer",
            ReportId::THROWN_KEG => "thrownKeg",
            ReportId::PUMP_UP_THE_CROWD_RE_ROLL => "pumpUpTheCrowdReRoll",
            ReportId::SHOW_STAR_RE_ROLL => "showStarReRoll",
            ReportId::BIASED_REF => "biasedRef",
            ReportId::WEATHER_MAGE_ROLL => "weatherMageRoll",
            ReportId::WEATHER_MAGE_RESULT => "weatherMageResult",
            ReportId::LOOK_INTO_MY_EYES_ROLL => "lookIntoMyEyesRoll",
            ReportId::BALEFUL_HEX => "balefulHex",
            ReportId::ALL_YOU_CAN_EAT => "allYouCanEat",
            ReportId::CATCH_OF_THE_DAY => "catchOfTheDay",
            ReportId::BREATHE_FIRE => "breatheFire",
            ReportId::THEN_I_STARTED_BLASTIN => "thenIStartedBlastin",
            ReportId::PRAYERS_AND_INDUCEMENTS_BOUGHT => "prayersAndInducementsBought",
            ReportId::THROW_AT_PLAYER => "throwAtPlayer",
            ReportId::STEADY_FOOTING_ROLL => "steadyFootingRoll",
            ReportId::MASCOT_USED => "mascotUsed",
            ReportId::TEAM_EVENT => "teamEvent",
            ReportId::TEAM_CAPTAIN_ROLL => "teamCaptainRoll",
            ReportId::GETTING_EVEN_ROLL => "gettingEvenRoll",
            ReportId::SABOTEUR_ROLL => "saboteurRoll",
            ReportId::CHOMP_ROLL => "chompRoll",
            ReportId::CHOMP_REMOVED => "chompRemoved",
            ReportId::PUNT_DIRECTION_ROLL => "puntDirectionRoll",
            ReportId::PUNT_DISTANCE_ROLL => "puntDistanceRoll",
            ReportId::SWOOP_DIRECTION_ROLL => "swoopDirectionRoll",
            ReportId::SWOOP_DISTANCE_ROLL => "swoopDistanceRoll",
        }
    }

    pub fn for_name(name: &str) -> Option<Self> {
        match name {
            "none" => Some(ReportId::NONE),
            "nervesOfSteel" => Some(ReportId::NERVES_OF_STEEL),
            "alwaysHungryRoll" => Some(ReportId::ALWAYS_HUNGRY_ROLL),
            "argueTheCall" => Some(ReportId::ARGUE_THE_CALL),
            "catchRoll" => Some(ReportId::CATCH_ROLL),
            "cloudBurster" => Some(ReportId::CLOUD_BURSTER),
            "confusionRoll" => Some(ReportId::CONFUSION_ROLL),
            "dauntlessRoll" => Some(ReportId::DAUNTLESS_ROLL),
            "dodgeRoll" => Some(ReportId::DODGE_ROLL),
            "escapeRoll" => Some(ReportId::ESCAPE_ROLL),
            "foulAppearanceRoll" => Some(ReportId::FOUL_APPEARANCE_ROLL),
            "goForItRoll" => Some(ReportId::GO_FOR_IT_ROLL),
            "interceptionRoll" => Some(ReportId::INTERCEPTION_ROLL),
            "leapRoll" => Some(ReportId::JUMP_ROLL),
            "passRoll" => Some(ReportId::PASS_ROLL),
            "pickUpRoll" => Some(ReportId::PICK_UP_ROLL),
            "rightStuffRoll" => Some(ReportId::RIGHT_STUFF_ROLL),
            "regenerationRoll" => Some(ReportId::REGENERATION_ROLL),
            "safeThrowRoll" => Some(ReportId::SAFE_THROW_ROLL),
            "tentaclesShadowingRoll" => Some(ReportId::TENTACLES_SHADOWING_ROLL),
            "skillUse" => Some(ReportId::SKILL_USE),
            "reRoll" => Some(ReportId::RE_ROLL),
            "turnEnd" => Some(ReportId::TURN_END),
            "playerAction" => Some(ReportId::PLAYER_ACTION),
            "foul" => Some(ReportId::FOUL),
            "handOver" => Some(ReportId::HAND_OVER),
            "injury" => Some(ReportId::INJURY),
            "apothecaryRoll" => Some(ReportId::APOTHECARY_ROLL),
            "apothecaryChoice" => Some(ReportId::APOTHECARY_CHOICE),
            "throwIn" => Some(ReportId::THROW_IN),
            "scatterBall" => Some(ReportId::SCATTER_BALL),
            "block" => Some(ReportId::BLOCK),
            "blockChoice" => Some(ReportId::BLOCK_CHOICE),
            "spectators" => Some(ReportId::SPECTATORS),
            "weather" => Some(ReportId::WEATHER),
            "coinThrow" => Some(ReportId::COIN_THROW),
            "receiveChoice" => Some(ReportId::RECEIVE_CHOICE),
            "kickoffResult" => Some(ReportId::KICKOFF_RESULT),
            "kickoffScatter" => Some(ReportId::KICKOFF_SCATTER),
            "extraReRoll" => Some(ReportId::KICKOFF_EXTRA_RE_ROLL),
            "kickoffRiot" => Some(ReportId::KICKOFF_RIOT),
            "kickoffTimeout" => Some(ReportId::KICKOFF_TIMEOUT),
            "solidDefenceRoll" => Some(ReportId::SOLID_DEFENCE_ROLL),
            "quickSnapRoll" => Some(ReportId::QUICK_SNAP_ROLL),
            "kickoffSequenceActivationsCount" => Some(ReportId::KICKOFF_SEQUENCE_ACTIVATIONS_COUNT),
            "kickoffSequenceActivationsExhausted" => Some(ReportId::KICKOFF_SEQUENCE_ACTIVATIONS_EXHAUSTED),
            "blitzRoll" => Some(ReportId::BLITZ_ROLL),
            "kickoffOfficiousRef" => Some(ReportId::KICKOFF_OFFICIOUS_REF),
            "officiousRefRoll" => Some(ReportId::OFFICIOUS_REF_ROLL),
            "kickoffThrowARock" => Some(ReportId::KICKOFF_THROW_A_ROCK),
            "pushback" => Some(ReportId::PUSHBACK),
            "referee" => Some(ReportId::REFEREE),
            "kickoffPitchInvasion" => Some(ReportId::KICKOFF_PITCH_INVASION),
            "dodgySnackRoll" => Some(ReportId::DODGY_SNACK_ROLL),
            "kickoffDodgySnack" => Some(ReportId::KICKOFF_DODGY_SNACK),
            "throwTeamMateRoll" => Some(ReportId::THROW_TEAM_MATE_ROLL),
            "dedicatedFans" => Some(ReportId::DEDICATED_FANS),
            "scatterPlayer" => Some(ReportId::SCATTER_PLAYER),
            "swoopPlayer" => Some(ReportId::SWOOP_PLAYER),
            "timeoutEnforced" => Some(ReportId::TIMEOUT_ENFORCED),
            "winnings" => Some(ReportId::WINNINGS),
            "winningsRoll" => Some(ReportId::WINNINGS_ROLL),
            "fumbblResultUpload" => Some(ReportId::FUMBBL_RESULT_UPLOAD),
            "fanFactorRoll" => Some(ReportId::FAN_FACTOR_ROLL_POST_MATCH),
            "mostValuablePlayers" => Some(ReportId::MOST_VALUABLE_PLAYERS),
            "defectingPlayers" => Some(ReportId::DEFECTING_PLAYERS),
            "jumpUpRoll" => Some(ReportId::JUMP_UP_ROLL),
            "standUpRoll" => Some(ReportId::STAND_UP_ROLL),
            "bribesRoll" => Some(ReportId::BRIBES_ROLL),
            "masterChefRoll" => Some(ReportId::MASTER_CHEF_ROLL),
            "startHalf" => Some(ReportId::START_HALF),
            "inducement" => Some(ReportId::INDUCEMENT),
            "pilingOn" => Some(ReportId::PILING_ON),
            "chainsawRoll" => Some(ReportId::CHAINSAW_ROLL),
            "leader" => Some(ReportId::LEADER),
            "secretWeaponBan" => Some(ReportId::SECRET_WEAPON_BAN),
            "bloodLustRoll" => Some(ReportId::BLOOD_LUST_ROLL),
            "hypnoticGazeRoll" => Some(ReportId::HYPNOTIC_GAZE_ROLL),
            "biteSpectator" => Some(ReportId::BITE_SPECTATOR),
            "animosityRoll" => Some(ReportId::ANIMOSITY_ROLL),
            "raiseDead" => Some(ReportId::RAISE_DEAD),
            "blockRoll" => Some(ReportId::BLOCK_ROLL),
            "penaltyShootout" => Some(ReportId::PENALTY_SHOOTOUT),
            "doubleHiredStarPlayer" => Some(ReportId::DOUBLE_HIRED_STAR_PLAYER),
            "doubleHiredStaff" => Some(ReportId::DOUBLE_HIRED_STAFF),
            "spellEffectRoll" => Some(ReportId::SPELL_EFFECT_ROLL),
            "wizardUse" => Some(ReportId::WIZARD_USE),
            "gameOptions" => Some(ReportId::GAME_OPTIONS),
            "passBlock" => Some(ReportId::PASS_BLOCK),
            "noPlayersToField" => Some(ReportId::NO_PLAYERS_TO_FIELD),
            "playCard" => Some(ReportId::PLAY_CARD),
            "cardDeactivated" => Some(ReportId::CARD_DEACTIVATED),
            "bombOutOfBounds" => Some(ReportId::BOMB_OUT_OF_BOUNDS),
            "pettyCash" => Some(ReportId::PETTY_CASH),
            "freePettyCash" => Some(ReportId::FREE_PETTY_CASH),
            "inducementsBought" => Some(ReportId::INDUCEMENTS_BOUGHT),
            "cardsBought" => Some(ReportId::CARDS_BOUGHT),
            "cardEffectRoll" => Some(ReportId::CARD_EFFECT_ROLL),
            "weepingDaggerRoll" => Some(ReportId::WEEPING_DAGGER_ROLL),
            "kickTeamMateRoll" => Some(ReportId::KICK_TEAM_MATE_ROLL),
            "riotousRookies" => Some(ReportId::RIOTOUS_ROOKIES),
            "swarmingPlayersRoll" => Some(ReportId::SWARMING_PLAYERS_ROLL),
            "passDeviate" => Some(ReportId::PASS_DEVIATE),
            "cardsAndInducementsBought" => Some(ReportId::CARDS_AND_INDUCEMENTS_BOUGHT),
            "fanFactor" => Some(ReportId::FAN_FACTOR),
            "selectBlitzTarget" => Some(ReportId::SELECT_BLITZ_TARGET),
            "selectGazeTarget" => Some(ReportId::SELECT_GAZE_TARGET),
            "bombExplodesAfterCatch" => Some(ReportId::BOMB_EXPLODES_AFTER_CATCH),
            "placedBallDirection" => Some(ReportId::PLACE_BALL_DIRECTION),
            "fumblerooskie" => Some(ReportId::FUMBLEROOSKIE),
            "animalSavagery" => Some(ReportId::ANIMAL_SAVAGERY),
            "projectileVomit" => Some(ReportId::PROJECTILE_VOMIT),
            "brilliantCoachingReRoll" => Some(ReportId::BRILLIANT_COACHING_RE_ROLLS_LOST),
            "pumpUpTheCrowdReRollLost" => Some(ReportId::PUMP_UP_THE_CROWD_RE_ROLLS_LOST),
            "showStarReRollLost" => Some(ReportId::SHOW_STAR_RE_ROLLS_LOST),
            "kickTeamMateFumble" => Some(ReportId::KICK_TEAM_MATE_FUMBLE),
            "blockReRoll" => Some(ReportId::BLOCK_RE_ROLL),
            "trapDoor" => Some(ReportId::TRAP_DOOR),
            "prayerAmount" => Some(ReportId::PRAYER_AMOUNT),
            "prayerRoll" => Some(ReportId::PRAYER_ROLL),
            "prayerEnd" => Some(ReportId::PRAYER_END),
            "prayerWasted" => Some(ReportId::PRAYER_WASTED),
            "cheeringFans" => Some(ReportId::KICKOFF_CHEERING_FANS),
            "briberyAndCorruptionReRoll" => Some(ReportId::BRIBERY_AND_CORRUPTION_RE_ROLL),
            "playerEvent" => Some(ReportId::PLAYER_EVENT),
            "stallerDetected" => Some(ReportId::STALLER_DETECTED),
            "throwAtStallingPlayer" => Some(ReportId::THROW_AT_STALLING_PLAYER),
            "indomitable" => Some(ReportId::INDOMITABLE),
            "oldPro" => Some(ReportId::OLD_PRO),
            "pickMeUp" => Some(ReportId::PICK_ME_UP),
            "skillWasted" => Some(ReportId::SKILL_WASTED),
            "twoForOne" => Some(ReportId::TWO_FOR_ONE),
            "modifiedPassResult" => Some(ReportId::MODIFIED_PASS_RESULT),
            "modifiedDodgeResultSuccessful" => Some(ReportId::MODIFIED_DODGE_RESULT_SUCCESSFUL),
            "raidingParty" => Some(ReportId::RAIDING_PARTY),
            "event" => Some(ReportId::EVENT),
            "hitAndRun" => Some(ReportId::HIT_AND_RUN),
            "skillUseOtherPlayer" => Some(ReportId::SKILL_USE_OTHER_PLAYER),
            "thrownKeg" => Some(ReportId::THROWN_KEG),
            "pumpUpTheCrowdReRoll" => Some(ReportId::PUMP_UP_THE_CROWD_RE_ROLL),
            "showStarReRoll" => Some(ReportId::SHOW_STAR_RE_ROLL),
            "biasedRef" => Some(ReportId::BIASED_REF),
            "weatherMageRoll" => Some(ReportId::WEATHER_MAGE_ROLL),
            "weatherMageResult" => Some(ReportId::WEATHER_MAGE_RESULT),
            "lookIntoMyEyesRoll" => Some(ReportId::LOOK_INTO_MY_EYES_ROLL),
            "balefulHex" => Some(ReportId::BALEFUL_HEX),
            "allYouCanEat" => Some(ReportId::ALL_YOU_CAN_EAT),
            "catchOfTheDay" => Some(ReportId::CATCH_OF_THE_DAY),
            "breatheFire" => Some(ReportId::BREATHE_FIRE),
            "thenIStartedBlastin" => Some(ReportId::THEN_I_STARTED_BLASTIN),
            "prayersAndInducementsBought" => Some(ReportId::PRAYERS_AND_INDUCEMENTS_BOUGHT),
            "throwAtPlayer" => Some(ReportId::THROW_AT_PLAYER),
            "steadyFootingRoll" => Some(ReportId::STEADY_FOOTING_ROLL),
            "mascotUsed" => Some(ReportId::MASCOT_USED),
            "teamEvent" => Some(ReportId::TEAM_EVENT),
            "teamCaptainRoll" => Some(ReportId::TEAM_CAPTAIN_ROLL),
            "gettingEvenRoll" => Some(ReportId::GETTING_EVEN_ROLL),
            "saboteurRoll" => Some(ReportId::SABOTEUR_ROLL),
            "chompRoll" => Some(ReportId::CHOMP_ROLL),
            "chompRemoved" => Some(ReportId::CHOMP_REMOVED),
            "puntDirectionRoll" => Some(ReportId::PUNT_DIRECTION_ROLL),
            "puntDistanceRoll" => Some(ReportId::PUNT_DISTANCE_ROLL),
            "swoopDirectionRoll" => Some(ReportId::SWOOP_DIRECTION_ROLL),
            "swoopDistanceRoll" => Some(ReportId::SWOOP_DISTANCE_ROLL),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_block() {
        let id = ReportId::BLOCK;
        assert_eq!(ReportId::for_name(id.get_name()), Some(id));
    }

    #[test]
    fn round_trip_injury() {
        let id = ReportId::INJURY;
        assert_eq!(ReportId::for_name(id.get_name()), Some(id));
    }

    #[test]
    fn round_trip_start_half() {
        let id = ReportId::START_HALF;
        assert_eq!(ReportId::for_name(id.get_name()), Some(id));
    }

    #[test]
    fn round_trip_pump_up_crowd() {
        let id = ReportId::PUMP_UP_THE_CROWD_RE_ROLL;
        assert_eq!(ReportId::for_name(id.get_name()), Some(id));
    }

    #[test]
    fn round_trip_chomp_removed() {
        let id = ReportId::CHOMP_REMOVED;
        assert_eq!(ReportId::for_name(id.get_name()), Some(id));
    }

    #[test]
    fn unknown_name_returns_none() {
        assert_eq!(ReportId::for_name("unknownReport"), None);
    }

    #[test]
    fn get_name_jump_roll_is_leap() {
        // Java ReportId.JUMP_ROLL has name "leapRoll" (legacy naming)
        assert_eq!(ReportId::JUMP_ROLL.get_name(), "leapRoll");
    }
}
