/// 1:1 translation of `com.fumbbl.ffb.server.factory.StepIdFactory`.
///
/// Maps Java camelCase step names (from serialized game state) to the Rust `StepId` enum.
/// Java iterates `StepId.values()` and matches by `getName()` or `getOldName()`.
/// Rust uses an explicit match for O(1) lookup.
use crate::step::framework::StepId;

pub struct StepIdFactory;

impl StepIdFactory {
    pub fn new() -> Self { Self }

    /// Java: `forName(String pName)` — case-insensitive lookup by Java step name.
    /// Returns `None` for unknown names (Java returns `null`).
    pub fn for_name(name: &str) -> Option<StepId> {
        // Normalize: Java uses equalsIgnoreCase
        match name.to_ascii_lowercase().as_str() {
            "allyoucaneat"              => Some(StepId::AllYouCanEat),
            "alwayshungry"              => Some(StepId::AlwaysHungry),
            "animalsavagery"            => Some(StepId::AnimalSavagery),
            "animosity"                 => Some(StepId::Animosity),
            "apothecary"                => Some(StepId::Apothecary),
            "apothecarymultiple"        => Some(StepId::ApothecaryMultiple),
            "applykickoffresult"        => Some(StepId::ApplyKickoffResult),
            "assigntouchdowns"          => Some(StepId::AssignTouchdowns),
            "autogazezoat"              => Some(StepId::AutoGazeZoat),
            "balefulhex"                => Some(StepId::BalefulHex),
            "blackink"                  => Some(StepId::BlackInk),
            "blitzturn"                 => Some(StepId::BlitzTurn),
            "blockballandchain"         => Some(StepId::BlockBallAndChain),
            "blockchainsaw"             => Some(StepId::BlockChainsaw),
            "blockchoice"               => Some(StepId::BlockChoice),
            "blockdodge"                => Some(StepId::BlockDodge),
            "blockroll"                 => Some(StepId::BlockRoll),
            "blockrollmultiple"         => Some(StepId::BlockRollMultiple),
            "blockstatistics"           => Some(StepId::BlockStatistics),
            "bloodlust"                 => Some(StepId::BloodLust),
            "bombardier"                => Some(StepId::Bombardier),
            "bonehead"                  => Some(StepId::BoneHead),
            "bothdown"                  => Some(StepId::BothDown),
            "breathefire"               => Some(StepId::BreatheFire),
            "bribes"                    => Some(StepId::Bribes),
            "buycards"                  => Some(StepId::BuyCards),
            "buycardsandinducements"    => Some(StepId::BuyCardsAndInducements),
            "buyinducements"            => Some(StepId::BuyInducements),
            "catchoftheday"             => Some(StepId::CatchOfTheDay),
            "catchscatterthrowin"       => Some(StepId::CatchScatterThrowIn),
            "chomp"                     => Some(StepId::Chomp),
            "checkstalling"             => Some(StepId::CheckStalling),
            "coinchoice"                => Some(StepId::CoinChoice),
            "consumeparameter"          => Some(StepId::ConsumeParameter),
            "dauntless"                 => Some(StepId::Dauntless),
            "dauntlessmultiple"         => Some(StepId::DauntlessMultiple),
            "dedicatedfans"             => Some(StepId::DedicatedFans),
            "dispatchdumpoff"           => Some(StepId::DispatchDumpOff),
            "dispatchpassing"           => Some(StepId::DispatchPassing),
            "dispatchscatterplayer"     => Some(StepId::DispatchScatterPlayer),
            "divingtackle"              => Some(StepId::DivingTackle),
            "doublestrength"            => Some(StepId::DoubleStrength),
            "droppiledriver player" | "dropactingplayer" => Some(StepId::DropActingPlayer),
            "dropdivingtackler"         => Some(StepId::DropDivingTackler),
            "dropfallingplayers"        => Some(StepId::DropFallingPlayers),
            "dumpoff"                   => Some(StepId::DumpOff),
            "eatteammate"               => Some(StepId::EatTeamMate),
            "ejectplayer"               => Some(StepId::EjectPlayer),
            "endblocking"               => Some(StepId::EndBlocking),
            "endbomb"                   => Some(StepId::EndBomb),
            "endfeeding"                => Some(StepId::EndFeeding),
            "endfouling"                => Some(StepId::EndFouling),
            "endfuriousoutburst"        => Some(StepId::EndFuriousOutburst),
            "endgame"                   => Some(StepId::EndGame),
            "endinducement"             => Some(StepId::EndInducement),
            "endkickteammate"           => Some(StepId::EndKickTeamMate),
            "endkickoff"                => Some(StepId::EndKickoff),
            "endmoving"                 => Some(StepId::EndMoving),
            "endpassing"                => Some(StepId::EndPassing),
            "endpunt"                   => Some(StepId::EndPunt),
            "endscatterplayer"          => Some(StepId::EndScatterPlayer),
            "endselecting"              => Some(StepId::EndSelecting),
            "endthrowteammate"          => Some(StepId::EndThrowTeamMate),
            "endthenistartedblastin" | "endthenistartedblastin" => Some(StepId::EndThenIStartedBlastin),
            "endthrowkeg"               => Some(StepId::EndThrowKeg),
            "endturn"                   => Some(StepId::EndTurn),
            "falldown"                  => Some(StepId::FallDown),
            "fanfactor"                 => Some(StepId::FanFactor),
            "firstmovefuriousoutburst"  => Some(StepId::FirstMoveFuriousOutburst),
            "followup"                  => Some(StepId::Followup),
            "forgonestalling"           => Some(StepId::ForgoneStalling),
            "foul"                      => Some(StepId::Foul),
            "foulappearance"            => Some(StepId::FoulAppearance),
            "foulappearancemultiple"    => Some(StepId::FoulAppearanceMultiple),
            "foulchainsaw"              => Some(StepId::FoulChainsaw),
            "fumblettmpass"             => Some(StepId::FumbleTtmPass),
            "gettingeven"               => Some(StepId::GettingEven),
            "goforit"                   => Some(StepId::GoForIt),
            "gotolabel"                 => Some(StepId::GotoLabel),
            "hailmarypass"              => Some(StepId::HailMaryPass),
            "handover"                  => Some(StepId::HandOver),
            "handledropplayercontext"   => Some(StepId::HandleDropPlayerContext),
            "hitandrun"                 => Some(StepId::HitAndRun),
            "horns"                     => Some(StepId::Horns),
            "hypnoticgaze"              => Some(StepId::HypnoticGaze),
            "initactivation" | "recoverfromgaze" => Some(StepId::InitActivation),
            "initblocking"              => Some(StepId::InitBlocking),
            "initbomb"                  => Some(StepId::InitBomb),
            "initendgame"               => Some(StepId::InitEndGame),
            "initfeeding"               => Some(StepId::InitFeeding),
            "initfouling"               => Some(StepId::InitFouling),
            "initinducement"            => Some(StepId::InitInducement),
            "initfuriousoutburst"       => Some(StepId::InitFuriousOutburst),
            "initlookintomyeyes"        => Some(StepId::InitLookIntoMyEyes),
            "initkickoff"               => Some(StepId::InitKickoff),
            "initmoving"                => Some(StepId::InitMoving),
            "initpassing"               => Some(StepId::InitPassing),
            "initpunt"                  => Some(StepId::InitPunt),
            "initscatterplayer"         => Some(StepId::InitScatterPlayer),
            "initselecting"             => Some(StepId::InitSelecting),
            "initstartgame"             => Some(StepId::InitStartGame),
            "initthrowteammate"         => Some(StepId::InitThrowTeamMate),
            "initkickteammate"          => Some(StepId::InitKickTeamMate),
            "intercept"                 => Some(StepId::Intercept),
            "juggernaut"                => Some(StepId::Juggernaut),
            "leap"                      => Some(StepId::Jump),
            "jumpup"                    => Some(StepId::JumpUp),
            "kickteammate"              => Some(StepId::KickTeamMate),
            "kickteammatedoublerolled"  => Some(StepId::KickTeamMateDoubleRolled),
            "kickoff"                   => Some(StepId::Kickoff),
            "kickoffscatterroll"        => Some(StepId::KickoffScatterRoll),
            "kickoffscatterrollaskafter" => Some(StepId::KickoffScatterRollAskAfter),
            "lookintomyeyes" | "lookintomyeyes2" | "lookintomyeyes3" => None, // placeholder
            _ if name.to_ascii_lowercase() == "lookintomyeyes" => Some(StepId::LookIntoMyEyes),
            "missedpass"                => Some(StepId::MissedPass),
            "masterchef"                => Some(StepId::MasterChef),
            "move"                      => Some(StepId::Move),
            "moveballandchain"          => Some(StepId::MoveBallAndChain),
            "movedodge"                 => Some(StepId::MoveDodge),
            "multimblockfork" | "multiblockfork" => Some(StepId::MultipleBlockFork),
            "mvp"                       => Some(StepId::Mvp),
            "nextstep"                  => Some(StepId::NextStep),
            "pass"                      => Some(StepId::Pass),
            "passblock"                 => Some(StepId::PassBlock),
            "penaltyshootout"           => Some(StepId::PenaltyShootout),
            "pettycash"                 => Some(StepId::PettyCash),
            "pickmеup" | "pickmeup"     => Some(StepId::PickMeUp),
            "pickup"                    => Some(StepId::PickUp),
            "piledriver"                => Some(StepId::PileDriver),
            "placeball"                 => Some(StepId::PlaceBall),
            "playcard"                  => Some(StepId::PlayCard),
            "playerloss"                => Some(StepId::PlayerLoss),
            "prayer"                    => Some(StepId::Prayer),
            "prayers"                   => Some(StepId::Prayers),
            "pro"                       => Some(StepId::Pro),
            "projectilevomit"           => Some(StepId::ProjectileVomit),
            "puntdirection"             => Some(StepId::PuntDirection),
            "puntdistance"              => Some(StepId::PuntDistance),
            "pushback"                  => Some(StepId::Pushback),
            "quickbite"                 => Some(StepId::QuickBite),
            "raidingparty"              => Some(StepId::RaidingParty),
            "reallystupid"              => Some(StepId::ReallyStupid),
            "receivechoice"             => Some(StepId::ReceiveChoice),
            "referee"                   => Some(StepId::Referee),
            "removetargetselectionstate" | "removeblitzstate" => Some(StepId::RemoveTargetSelectionState),
            "reportinjury"              => Some(StepId::ReportStabInjury),
            "resetfumblerooskie"        => Some(StepId::ResetFumblerooskie),
            "resettomove"               => Some(StepId::ResetToMove),
            "resolvebomb"               => Some(StepId::ResolveBomb),
            "resolvepass"               => Some(StepId::ResolvePass),
            "rightstuff"                => Some(StepId::RightStuff),
            "riotousrookies"            => Some(StepId::RiotousRookies),
            "safethrow"                 => Some(StepId::SafeThrow),
            "secondmovefuriousoutburst" => Some(StepId::SecondMoveFuriousOutburst),
            "selectblitztarget"         => Some(StepId::SelectBlitzTarget),
            "selectblitztargetend"      => Some(StepId::SelectBlitzTargetEnd),
            "selectgazetarget"          => Some(StepId::SelectGazeTarget),
            "selectgazetargetend"       => Some(StepId::SelectGazeTargetEnd),
            "setup"                     => Some(StepId::Setup),
            "setactingteam"             => Some(StepId::SetActingTeam),
            "setactingplayerandteam"    => Some(StepId::SetActingPlayerAndTeam),
            "setdefender"               => Some(StepId::SetDefender),
            "shadowing"                 => Some(StepId::Shadowing),
            "spectators"                => Some(StepId::Spectators),
            "specialeffect"             => Some(StepId::SpecialEffect),
            "stab"                      => Some(StepId::Stab),
            "stallingplayer"            => Some(StepId::StallingPlayer),
            "standup"                   => Some(StepId::StandUp),
            "steadyfooting"             => Some(StepId::SteadyFooting),
            "swarming"                  => Some(StepId::Swarming),
            "swoop"                     => Some(StepId::Swoop),
            "takeroot"                  => Some(StepId::TakeRoot),
            "tentacles"                 => Some(StepId::Tentacles),
            "thenistartedblastin"       => Some(StepId::ThenIStartedBlastin),
            "throwarock"                => Some(StepId::ThrowARock),
            "throwkeg"                  => Some(StepId::ThrowKeg),
            "throwteammate"             => Some(StepId::ThrowTeamMate),
            "trapdoor"                  => Some(StepId::TrapDoor),
            "treacherous"               => Some(StepId::Treacherous),
            "trickster"                 => Some(StepId::Trickster),
            "touchback"                 => Some(StepId::Touchback),
            "unchanmelledfury" | "unchannelledfury" => Some(StepId::UnchannelledFury),
            "weather"                   => Some(StepId::Weather),
            "weathermage"               => Some(StepId::WeatherMage),
            "wildanimal"                => Some(StepId::WildAnimal),
            "winnings"                  => Some(StepId::Winnings),
            "wisdomofthewhitedwarf"     => Some(StepId::WisdomOfTheWhiteDwarf),
            "wizard"                    => Some(StepId::Wizard),
            "wrestle"                   => Some(StepId::Wrestle),
            _                           => None,
        }
    }

    /// Reverse mapping: Java step name for a given `StepId`.
    /// Used for serialization (save/restore game state).
    pub fn name_for(id: StepId) -> &'static str {
        match id {
            StepId::AllYouCanEat             => "allYouCanEat",
            StepId::AlwaysHungry             => "alwaysHungry",
            StepId::AnimalSavagery           => "animalSavagery",
            StepId::Animosity                => "animosity",
            StepId::Apothecary               => "apothecary",
            StepId::ApothecaryMultiple       => "apothecaryMultiple",
            StepId::ApplyKickoffResult       => "applyKickoffResult",
            StepId::AssignTouchdowns         => "assignTouchdowns",
            StepId::AutoGazeZoat             => "autoGazeZoat",
            StepId::BalefulHex               => "balefulHex",
            StepId::BlackInk                 => "blackInk",
            StepId::BlitzTurn                => "blitzTurn",
            StepId::BlockBallAndChain        => "blockBallAndChain",
            StepId::BlockChainsaw            => "blockChainsaw",
            StepId::BlockChoice              => "blockChoice",
            StepId::BlockDodge               => "blockDodge",
            StepId::BlockRoll                => "blockRoll",
            StepId::BlockRollMultiple        => "blockRollMultiple",
            StepId::BlockStatistics          => "blockStatistics",
            StepId::BloodLust                => "bloodLust",
            StepId::Bombardier               => "bombardier",
            StepId::Bombardier2              => "bombardier",
            StepId::BoneHead                 => "boneHead",
            StepId::BothDown                 => "bothDown",
            StepId::BreatheFire              => "breatheFire",
            StepId::Bribes                   => "bribes",
            StepId::BuyCards                 => "buyCards",
            StepId::BuyCardsAndInducements   => "buyCardsAndInducements",
            StepId::BuyInducements           => "buyInducements",
            StepId::CatchOfTheDay            => "catchOfTheDay",
            StepId::CatchScatterThrowIn      => "catchScatterThrowIn",
            StepId::Chomp                    => "chomp",
            StepId::CheckStalling            => "checkStalling",
            StepId::CoinChoice               => "coinChoice",
            StepId::ConsumeParameter         => "consumeParameter",
            StepId::Dauntless                => "dauntless",
            StepId::DauntlessMultiple        => "dauntlessMultiple",
            StepId::DedicatedFans            => "dedicatedFans",
            StepId::DispatchDumpOff          => "dispatchDumpOff",
            StepId::DispatchPassing          => "dispatchPassing",
            StepId::DispatchScatterPlayer    => "dispatchScatterPlayer",
            StepId::DivingTackle             => "divingTackle",
            StepId::DoubleStrength           => "doubleStrength",
            StepId::DropActingPlayer         => "dropPileDriverPlayer",
            StepId::DropDivingTackler        => "dropDivingTackler",
            StepId::DropFallingPlayers       => "dropFallingPlayers",
            StepId::DumpOff                  => "dumpOff",
            StepId::EatTeamMate              => "eatTeamMate",
            StepId::EjectPlayer              => "ejectPlayer",
            StepId::EndBlocking              => "endBlocking",
            StepId::EndBomb                  => "endBomb",
            StepId::EndFeeding               => "endFeeding",
            StepId::EndFouling               => "endFouling",
            StepId::EndFuriousOutburst       => "endFuriousOutburst",
            StepId::EndGame                  => "endGame",
            StepId::EndInducement            => "endInducement",
            StepId::EndKickTeamMate          => "endKickTeamMate",
            StepId::EndKickoff               => "endKickoff",
            StepId::EndMoving                => "endMoving",
            StepId::EndPassing               => "endPassing",
            StepId::EndPunt                  => "endPunt",
            StepId::EndScatterPlayer         => "endScatterPlayer",
            StepId::EndSelecting             => "endSelecting",
            StepId::EndThrowTeamMate         => "endThrowTeamMate",
            StepId::EndThenIStartedBlastin   => "endThenIStartedBlastin",
            StepId::EndThrowKeg              => "endThrowKeg",
            StepId::EndPlayerAction          => "endPlayerAction",
            StepId::EndTurn                  => "endTurn",
            StepId::FallDown                 => "fallDown",
            StepId::FanFactor                => "fanFactor",
            StepId::FirstMoveFuriousOutburst => "firstMoveFuriousOutburst",
            StepId::Followup                 => "followup",
            StepId::ForgoneStalling          => "forgoneStalling",
            StepId::Foul                     => "foul",
            StepId::FoulAppearance           => "foulAppearance",
            StepId::FoulAppearanceMultiple   => "foulAppearanceMultiple",
            StepId::FoulChainsaw             => "foulChainsaw",
            StepId::FumbleTtmPass            => "fumbleTtmPass",
            StepId::GettingEven              => "gettingEven",
            StepId::GoForIt                  => "goForIt",
            StepId::GotoLabel                => "gotoLabel",
            StepId::HailMaryPass             => "hailMaryPass",
            StepId::HandOver                 => "handOver",
            StepId::HandleDropPlayerContext  => "handleDropPlayerContext",
            StepId::HitAndRun                => "hitAndRun",
            StepId::Horns                    => "horns",
            StepId::HypnoticGaze             => "hypnoticGaze",
            StepId::InitActivation           => "initActivation",
            StepId::InitBlocking             => "initBlocking",
            StepId::InitBomb                 => "initBomb",
            StepId::InitEndGame              => "initEndGame",
            StepId::InitFeeding              => "initFeeding",
            StepId::InitFouling              => "initFouling",
            StepId::InitInducement           => "initInducement",
            StepId::InitFuriousOutburst      => "initFuriousOutburst",
            StepId::InitLookIntoMyEyes       => "initLookIntoMyEyes",
            StepId::InitKickoff              => "initKickoff",
            StepId::InitMoving               => "initMoving",
            StepId::InitPassing              => "initPassing",
            StepId::InitPunt                 => "initPunt",
            StepId::InitScatterPlayer        => "initScatterPlayer",
            StepId::InitSelecting            => "initSelecting",
            StepId::InitStartGame            => "initStartGame",
            StepId::InitThrowTeamMate        => "initThrowTeamMate",
            StepId::InitKickTeamMate         => "initKickTeamMate",
            StepId::Intercept                => "intercept",
            StepId::Juggernaut               => "juggernaut",
            StepId::Jump                     => "leap",
            StepId::JumpUp                   => "jumpUp",
            StepId::KickTeamMate             => "kickTeamMate",
            StepId::KickTeamMateDoubleRolled => "kickTeamMateDoubleRolled",
            StepId::Kickoff                  => "kickoff",
            StepId::KickoffScatterRoll       => "kickoffScatterRoll",
            StepId::KickoffScatterRollAskAfter => "kickoffScatterRollAskAfter",
            StepId::KickoffAnimation         => "kickoffAnimation",
            StepId::KickoffResultRoll        => "kickoffResultRoll",
            StepId::KickoffReturn            => "kickoffReturn",
            StepId::LookIntoMyEyes           => "lookIntoMyEyes",
            StepId::MissedPass               => "missedPass",
            StepId::MasterChef               => "masterChef",
            StepId::Move                     => "move",
            StepId::MoveBallAndChain         => "moveBallAndChain",
            StepId::MoveDodge                => "moveDodge",
            StepId::MultipleBlockFork        => "multiBlockFork",
            StepId::Mvp                      => "mvp",
            StepId::NextStep                 => "nextStep",
            StepId::NoOp                     => "noOp",
            StepId::Pass                     => "pass",
            StepId::PassBlock                => "passBlock",
            StepId::PenaltyShootout          => "penaltyShootout",
            StepId::PettyCash                => "pettyCash",
            StepId::PickMeUp                 => "pickMeUp",
            StepId::PickUp                   => "pickUp",
            StepId::PileDriver               => "pileDriver",
            StepId::PlaceBall                => "placeBall",
            StepId::PlayCard                 => "playCard",
            StepId::PlayerLoss               => "playerLoss",
            StepId::Prayer                   => "prayer",
            StepId::Prayers                  => "prayers",
            StepId::PrayerRoll               => "prayerRoll",
            StepId::Pro                      => "pro",
            StepId::ProjectileVomit          => "projectileVomit",
            StepId::PuntDirection            => "puntDirection",
            StepId::PuntDistance             => "puntDistance",
            StepId::Pushback                 => "pushback",
            StepId::QuickBite                => "quickBite",
            StepId::RaidingParty             => "raidingParty",
            StepId::ReallyStupid             => "reallyStupid",
            StepId::ReceiveChoice            => "receiveChoice",
            StepId::Referee                  => "referee",
            StepId::RemoveTargetSelectionState => "removeTargetSelectionState",
            StepId::ReportStabInjury         => "reportInjury",
            StepId::RecheckExplodeSkill      => "recheckExplodeSkill",
            StepId::ResetFumblerooskie       => "resetFumblerooskie",
            StepId::ResetToMove              => "resetToMove",
            StepId::ResolveBomb              => "resolveBomb",
            StepId::ResolvePass              => "resolvePass",
            StepId::RevertEndTurn            => "revertEndTurn",
            StepId::RightStuff               => "rightStuff",
            StepId::RiotousRookies           => "riotousRookies",
            StepId::SafeThrow                => "safeThrow",
            StepId::SecondMoveFuriousOutburst => "secondMoveFuriousOutburst",
            StepId::SelectBlitzTarget        => "selectBlitzTarget",
            StepId::SelectBlitzTargetEnd     => "selectBlitzTargetEnd",
            StepId::SelectGazeTarget         => "selectGazeTarget",
            StepId::SelectGazeTargetEnd      => "selectGazeTargetEnd",
            StepId::Setup                    => "setup",
            StepId::SetActingTeam            => "setActingTeam",
            StepId::SetActingPlayerAndTeam   => "setActingPlayerAndTeam",
            StepId::SetDefender              => "setDefender",
            StepId::Shadowing                => "shadowing",
            StepId::Spectators               => "spectators",
            StepId::SpecialEffect            => "specialEffect",
            StepId::Stab                     => "stab",
            StepId::StallingPlayer           => "stallingPlayer",
            StepId::StandUp                  => "standUp",
            StepId::StateMultipleRolls       => "stateMultipleRolls",
            StepId::SteadyFooting            => "steadyFooting",
            StepId::Swarming                 => "swarming",
            StepId::Swoop                    => "swoop",
            StepId::TakeRoot                 => "takeRoot",
            StepId::Tentacles                => "tentacles",
            StepId::ThenIStartedBlastin      => "thenIStartedBlastin",
            StepId::ThrowARock               => "throwARock",
            StepId::ThrowKeg                 => "throwKeg",
            StepId::ThrowTeamMate            => "throwTeamMate",
            StepId::TrapDoor                 => "trapDoor",
            StepId::Treacherous              => "treacherous",
            StepId::Trickster                => "trickster",
            StepId::Touchback                => "touchback",
            StepId::UnchannelledFury         => "unchannelledFury",
            StepId::Weather                  => "weather",
            StepId::WeatherMage              => "weatherMage",
            StepId::WildAnimal               => "wildAnimal",
            StepId::Winnings                 => "winnings",
            StepId::WisdomOfTheWhiteDwarf    => "wisdomOfTheWhiteDwarf",
            StepId::Wizard                   => "wizard",
            StepId::Wrestle                  => "wrestle",
        }
    }
}

impl Default for StepIdFactory {
    fn default() -> Self { Self::new() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn for_name_init_start_game() {
        assert_eq!(StepIdFactory::for_name("initStartGame"), Some(StepId::InitStartGame));
    }

    #[test]
    fn for_name_case_insensitive() {
        assert_eq!(StepIdFactory::for_name("INITSTARTGAME"), Some(StepId::InitStartGame));
        assert_eq!(StepIdFactory::for_name("BlockRoll"), Some(StepId::BlockRoll));
    }

    #[test]
    fn for_name_old_name_init_activation() {
        assert_eq!(StepIdFactory::for_name("recoverFromGaze"), Some(StepId::InitActivation));
    }

    #[test]
    fn for_name_old_name_remove_target_selection_state() {
        assert_eq!(StepIdFactory::for_name("removeBlitzState"), Some(StepId::RemoveTargetSelectionState));
    }

    #[test]
    fn for_name_report_stab_injury_old_name() {
        assert_eq!(StepIdFactory::for_name("reportInjury"), Some(StepId::ReportStabInjury));
    }

    #[test]
    fn for_name_unknown_returns_none() {
        assert_eq!(StepIdFactory::for_name("notAStep"), None);
    }

    #[test]
    fn name_for_block_roll_roundtrip() {
        let name = StepIdFactory::name_for(StepId::BlockRoll);
        assert_eq!(StepIdFactory::for_name(name), Some(StepId::BlockRoll));
    }

    #[test]
    fn name_for_init_start_game_roundtrip() {
        let name = StepIdFactory::name_for(StepId::InitStartGame);
        assert_eq!(StepIdFactory::for_name(name), Some(StepId::InitStartGame));
    }
}
